### ISSUE TITLE
Build error on XCode

### ISSUE THREAD

**Issue by vspedr** [idehub/react-native-google-analytics-bridge#101]
It's certainly a silly mistake by me, but I'll be glad if someone could help me with this.
I managed to set this module on Android just fine, by following the instructions using `react-native link react-native-google-analytics-bridge`. But in my iOS project, I get a build error like this, either by using `react-native link` or by following the [manual installation steps](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Manual-installation):

<img width="255" alt="screen shot 2017-01-18 at 08 45 23" src="https://cloud.githubusercontent.com/assets/9813942/22061157/dd3be216-dd5a-11e6-81cf-39c8b6e07315.png">

```#import <React/RCTBridgeModule.h> // error at this line
#import "TAGContainer.h"
#import "TagContainerOpener.h"
#import "TAGManager.h"
#import <React/RCTUtils.h>

@interface RCTGoogleTagManagerBridge : NSObject <RCTBridgeModule>

@property (nonatomic, strong) TAGManager *tagManager;
@property (nonatomic, strong) TAGContainer *container;
@property (nonatomic, copy) RCTPromiseResolveBlock openContainerResolver;

@end
```

Any ideas?
Edit: Using React Native @ 0.32

**Comment by cbrevik** [comment]
Hi @vspedr! The latest version of this module only supports React Native 0.40 and up. You will have to use version `4.0.3` of this module.

**Comment by vspedr** [comment]
Hey @cbrevik, thanks for the quick reply! I will try that and close this issue for now.
