### ISSUE TITLE
Including in Multiple Components

### ISSUE THREAD

**Issue by claykohut** [idehub/react-native-google-analytics-bridge#104]
What's the best method here -- do I need to init a new tracker for each component like below?
```
import {
  GoogleAnalyticsTracker
} from 'react-native-google-analytics-bridge';

const gaTracker = new GoogleAnalyticsTracker(MY_TRACKER_ID)
gaTracker.trackEvent('testcategory', 'testaction');
```
Will this duplicate the event tracking if I have multiple trackers with the same ID spread across different components?

I've seen elsewhere in the issues section where people suggest you don't have to do this but I can't seem to figure out how.

**Comment by cbrevik** [comment]
I definitely recommend wrapping the tracker in its own file, and initializing it once. 

This can be done as easily as

```javascript
import {
  GoogleAnalyticsTracker
} from 'react-native-google-analytics-bridge';

const gaTracker = new GoogleAnalyticsTracker(MY_TRACKER_ID)
export default gaTracker;
```

In a file called `MyTracker.js` (or whatever). And then `import MyTracker from './MyTracker'` in another file and call the functions as normal. Then the tracker will be initialized only once.

**Comment by claykohut** [comment]
Your solution works perfectly -- thanks!
