### ISSUE TITLE
Is setUser persisting userId?

### ISSUE THREAD

**Issue by henrikra** [idehub/react-native-google-analytics-bridge#105]
Meaning that do I have to use `setUser` always when user has logged in to my app. Or does react-native-google-analytics-bridge put `userId` to some AsyncStorage of some kind when `setUser` is called? So I don't have to set user every time the app starts?

**Comment by cbrevik** [comment]
Hi @henrikra,

No, `AsyncStorage` is not used. This module does not persist anything: https://github.com/idehub/react-native-google-analytics-bridge/blob/master/src/GoogleAnalyticsTracker.js#L150
