### ISSUE TITLE
_reactNativeGoogleAnalyticsBridge2.default is not a constructor

### ISSUE THREAD

**Issue by adamgeoffrion** [idehub/react-native-google-analytics-bridge#106]
Hi, I working with the v4.0.0 as I am on RN .39 (or .38). I have included the binary libraries and I have done an import on my router and I am trying to 

```
import GoogleAnalyticsTracker from 'react-native-google-analytics-bridge'

class NavigationRouter extends Component {
  render () {
    let tracker = new GoogleAnalyticsTracker('UA-12345-2');
    return (
      <Router>
        ...
      </Router>
    )
  }
}
```

However on the line I am calling the GoogleAnalyticsTracker constructor I get the error:

`_reactNativeGoogleAnalyticsBridge2.default is not a constructor`

Any thoughts?

**Comment by cbrevik** [comment]
Your import is incorrect, it should be `import { GoogleAnalyticsTracker } from 'react-native-google-analytics-bridge';`.

Doing it the way you have, you're importing GoogleAnalyticsBackwardsCompability, which is an already constructed object. Hence your error.

**Comment by adamgeoffrion** [comment]
Thanks! That was it.
