### ISSUE TITLE
Android throwing error when GoogleAnalytics dependency included

### ISSUE THREAD

**Issue by keerthanarbt** [idehub/react-native-google-analytics-bridge#108]
In React-native 
Execution failed for task ':app:dexDebug'.
> outDexFolder must be a folder

**Comment by cbrevik** [comment]
Hi @keerthanarbt. Is that the whole error message? If you have other modules in your RN project which also depends on Play Services, I'd recommend look at the troubleshooting wiki: https://github.com/idehub/react-native-google-analytics-bridge/wiki/Troubleshooting#android-build-problem
