### ISSUE TITLE
Does not appear to be compatible with RN 0.19 + iOS 8.4

### ISSUE THREAD

**Issue by lrettig** [idehub/react-native-google-analytics-bridge#11]
After upgrading to RN 0.19 just now, this plugin, which was working beautifully before, is suddenly dying with errors in both Xcode and JavaScript. It appears to work in iOS 9 but not in iOS 8.4 Does it require iOS 9?

```
2016-02-04 15:33:37.460 Breeze[59031:12725572] WARNING: GoogleAnalytics 3.15 void GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:48): Uncaught exception: *** -[__NSArrayI objectAtIndex:]: index 0 beyond bounds for empty array
2016-02-04 15:33:37.460 Breeze[59031:12721987] WARNING: GoogleAnalytics 3.15 void GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:44): Bailing on multiple uncaught exceptions: *** -[__NSArrayI objectAtIndex:]: index 0 beyond bounds for empty array
2016-02-04 15:33:37.461 Breeze[59031:12721987] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
	0   CoreFoundation                      0x01c65746 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x0106fa97 objc_exception_throw + 44
	2   CoreFoundation                      0x01b46cb2 -[__NSArrayI objectAtIndex:] + 210
	3   CoreFoundation                      0x01bb1df8 -[NSArray objectAtIndexedSubscript:] + 40
	4   Breeze                              0x001fc4e2 -[RCTBatchedBridge _handleRequestNumber:moduleID:methodID:params:] + 498
	5   Breeze                              0x001fb2c6 __33-[RCTBatchedBridge handleBuffer:]_block_invoke461 + 1062
	6   libdispatch.dylib                   0x049f95ea _dispatch_call_block_and_release + 15
	7   libdispatch.dylib                   0x04a1bbef _dispatch_client_callout + 14
	8   libdispatch.dylib                   0x049ffd61 _dispatch_queue_drain + 544
	9   libdispatch.dylib                   0x049ff9cb _dispatch_queue_invoke + 212
	10  libdispatch.dylib                   0x04a03012 _dispatch_root_queue_drain + 615
	11  libdispatch.dylib                   0x04a04b70 _dispatch_worker_thread3 + 115
	12  libsystem_pthread.dylib             0x04d6043e _pthread_wqthread + 1050
	13  libsystem_pthread.dylib             0x04d5df72 start_wqthread + 34
)
libc++abi.dylib: terminating with uncaught exception of type NSException
2016-02-04 15:33:37.462 Breeze[59031:12721758] WARNING: GoogleAnalytics 3.15 void GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:44): Bailing on multiple uncaught exceptions: *** -[__NSArrayI objectAtIndex:]: index 0 beyond bounds for empty array
```

```
Unhandled JS Exception: Cannot read property 'trackScreenView' of undefined
reactConsoleError @ ExceptionsManager.js:76
console.error @ YellowBox.js:49
logIfNoNativeHook @ RCTLog.js:38
__callFunction @ MessageQueue.js:183
(anonymous function) @ MessageQueue.js:87
guard @ MessageQueue.js:41
callFunctionReturnFlushedQueue @ MessageQueue.js:86
onmessage @ debuggerWorker.js:39
```

I'll investigate further to see if anything else might have caused this. Thanks.

**Comment by cbrevik** [comment]
Hi, thanks for the feedback!

The default target for this plugin is iOS 7.0 (like most React Native projects), so there should be no reason for it not working in 8.4.
While I have not yet tested this plugin with RN 0.19 yet. But, I have upgraded another project to RN 0.19, and seen a few esoteric errors. Seems especially to be associated with older RN projects being upgraded.

I'm going on a trip today so probably won't be able to look at this until over the weekend. 
But, just to help troubleshooting, can you attempt to create a new RN project (`react-native init`) with 0.19, and install this plugin there? Would be good to narrow it down, see if it is a more general error or not.

I'll bring a laptop and see what I can get done on the plane, but cannot promise anything. :)

**Comment by cbrevik** [comment]
Hi again @lrettig! 

Back again here, and did a quick test in a RN 0.19 project, and switched between iOS 7.0, 8.4 and 9.2.

I am unable to replicate the problem though. Are you experiencing the same thing if you [clone this project](https://github.com/cbrevik/ga-rn019), `npm install` and then run it?

**Comment by lrettig** [comment]
Hi @cbrevik thanks again for looking into this. Will give it a shot today and let you know.

**Comment by lrettig** [comment]
Confirmed that your code works fine in iOS 8.4 and 9.2. I tried recompiling my own project for 8.4, and it's now working fine, with no warnings or errors. Odd. Xcode used to complain that this library, and a couple of others, were "built for a newer version of iOS." Now it doesn't. I don't know what changed.

Thanks again for looking into this, and sorry for the false alarm. The issue appears to be on my end!

**Comment by cbrevik** [comment]
Good, glad it worked out! 

The warning you used to get before is related to RN projects specifically targetting iOS 7.0. 
A couple of versions ago I changed this project to explicitly target iOS 7.0 as well, so that is probably why the warning disappeared.
