### ISSUE TITLE
Cannot compile after upgrading RN and GAB

### ISSUE THREAD

**Issue by RemeJuan** [idehub/react-native-google-analytics-bridge#110]
I was somewhat behind on RN as an update broke a feature I needed, so I began upgrading everything now that it was fixed, everything was working fine but needed to bump GAB for iOS to build, after doing that I can no longer get android to build.

I hit the troubleshooting guide for play-services, but that does not seem like the issue, none of my modules have hard version depandancies on play services.

Only RNDeviceInfo which is
`com.google.android.gms:play-services-gcm:+`

But looking closer at the logs it looks me like it is trying to find images and cannot.

```
D:\Documents\Projects\cycle-culture-app-react\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawabl
e\common_google_signin_btn_icon_dark_normal.xml:3:29-91 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_normal_background').
D:\Documents\Projects\cycle-culture-app-react\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawabl
e\common_google_signin_btn_icon_light_normal.xml:3:29-92 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_normal_background')
.
D:\Documents\Projects\cycle-culture-app-react\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawabl
e\common_google_signin_btn_text_dark_normal.xml:3:29-91 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_normal_background').
D:\Documents\Projects\cycle-culture-app-react\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawabl
e\common_google_signin_btn_text_light_normal.xml:3:29-92 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_normal_background')
.

:react-native-google-analytics-bridge:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-google-analytics-bridge:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\remelh\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe'' finished with
 non-zero exit value 1
```

**Comment by cbrevik** [comment]
Hi @RemeJuan. 

I'd still try to hardcode a version for your modules in case they are in fact using different `play-services`.  When you say the troubleshooting guide, you mean you've tried this one right?: https://github.com/idehub/react-native-google-analytics-bridge/wiki/Troubleshooting

**Comment by RemeJuan** [comment]
@cbrevik That is the one, I tried hard-codeing as well, copied that piece of code u used, and bumped the version a few times too

There is only 1 mod referencing play services within my entire application.
I have also tried remove GA and it builds fine, restoring GA and removing every other module still fails.

**Comment by cbrevik** [comment]
Sorry I misunderstood, I thought you were using RNDeviceInfo as well? Would you mind posting the dependencies-section of your `app/build.gradle`?

Which versions of React Native & this module are you using?

Do you get the same build problem if you do `react-native init` and install it in a new app?

Also what do you mean by:
>  yet I can no longer use 3 for iOS, while I can use it for Android.

**Comment by RemeJuan** [comment]
```
RNDevice info doe snot have a specified version dependency, like urs it simply uses whatever is latest.

RN: 41.2
RNGAB: 5.0.1

It works fine if I spin up a new application with just the module loaded as an extra, that was what promted me to try removing all other modules from my app to see if there was some arb conflict.

iOS would not longer build with V3 of RNGAB installed, I had to upgrade to make it work. It was throwing errors with the module on build time, cannot remember what they were, this was last Thursday.

dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-google-analytics-bridge')
    compile project(':react-native-device-info')
    compile project(':RNSendIntentModule')
    compile project(':react-native-vector-icons')
    compile project(':react-native-code-push')
}
```

**Comment by cbrevik** [comment]
Yeah the RN team introduced a breaking change in v0.40 which means that you will have to use RNGAB v5.0+ for newer RN apps. 

But, just to understand completely. What you're saying is that when using this module alone in your upgraded app, it fails to build. But, when this module alone in a newly created app, it will build fine?

Have you attempted to nuke your node_modules folder and re-install in your upgraded app?

**Comment by RemeJuan** [comment]
> But, just to understand completely. What you're saying is that when using this module alone in your upgraded app, it fails to build. But, when this module alone in a newly created app, it will build fine?

Correct.

> Have you attempted to nuke your node_modules folder and re-install in your upgraded app?
A few times, on multiple computers.

I have even checked with the native android devs at work and they all confused, the files are there.

Even tried copying the node modules folder from the test application where it worked into this application to be 100% sure all the files where there.

This is something really silly, probably being caused by something super obscure, that makes no sense

**Comment by cbrevik** [comment]
Well, I see from your comment in #112 you're using Windows. File path length might be an issue for all I know.

Does the same thing occur with a new app if it has the same location in your projects folder, and a long project name, like this project?

And when you copied over then `node_modules` folder, you completely deleted the old one right?

**Comment by RemeJuan** [comment]
Total ID10T error, cannot believe I never tried that, making the folder name shorter fixed it. nerf.

Thanks
