### ISSUE TITLE
File Path too long - windows

### ISSUE THREAD

**Issue by Lloydza** [idehub/react-native-google-analytics-bridge#112]
On windows there is a file path issue (over 240 characters). My root directory is extremely short (c:\dev\project-root), and with that its 241 characters. For now I have made it even shorter, but it would be nice to fix this.

See below:

Execution failed for task ':react-native-google-analytics-bridge:mergeReleaseResources'.                                                                                                                                                     
> C:\dev\project-root\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png: Error: File path too long on Windows, keep below 240 characters : C:\dev\project-root\node_modules\react-native-google-analytics-bridge\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.0\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

**Comment by RemeJuan** [comment]
Strange, my project path name is quite a bit longer and I do not run into this issue.

I am now wondering if it is perhaps the reason for my issue... mmm

**Comment by cbrevik** [comment]
Hi, I have to kind of apologize for the long module name. It was just a "working title" name, but we kind of stuck with it. I don't think I can do anything about that at this point though.

**Comment by cbrevik** [comment]
Closing as it can't be fixed.

**Comment by waqas19921** [comment]
@cbrevik Can you change Longer file names ?
like `common_google_signin_btn_icon_light_normal_background.9.png`

**Comment by cbrevik** [comment]
@waqas19921 That file is part of the Google Play services SDK, and not a file I've specifically included: https://developers.google.com/android/reference/com/google/android/gms/R.drawable.html#common_google_signin_btn_icon_light_normal_background
