### ISSUE TITLE
undefined is not an object (evaluating '_NativeBridges.GoogleAnalyticsBridge.trackScreenView')

### ISSUE THREAD

**Issue by gsdias** [idehub/react-native-google-analytics-bridge#113]
"react-native": "0.41.2",
"react-native-google-analytics-bridge": "^5.0.1",

I have listed in Link Binary With Libraries the required ones:
- CoreData.Framework
- libsqlite3.0.tbd
- SystemConfiguration.framework
- libz.tbd
- libRCTGoogleAnalyticsBridge.a

let tracker = new GoogleAnalyticsTracker('UA-XXXXXXXX-X');

and when I execute `tracker.trackScreenView(currScreen);` I got the error
```
undefined is not an object (evaluating '_NativeBridges.GoogleAnalyticsBridge.trackScreenView')
Unhandled JS Exception: undefined is not an object (evaluating '_NativeBridges.GoogleAnalyticsBridge.trackScreenView')
```

Any idea what it might be?

**Comment by cbrevik** [comment]
Hi @gsdias. Thanks for opening an issue.

Just for posterity I'll repeat what I said in e-mail:
> Normally this is a result of improper setup of the module. I'd recommend reviewing the manual installation guide; https://github.com/idehub/react-native-google-analytics-bridge/wiki/Manual-installation
> In some instances a simple clean/rebuild and restarting Xcode/simulator/app will fix it.

Can you also post a more complete code example, where are you using this, and how are you importing the tracker? Have you tried to step through with the Chrome debugger?

If this is iOS, and you're using multiple targets, I'd recommend checking out [this comment](https://github.com/idehub/react-native-google-analytics-bridge/issues/59#issuecomment-254229071).

**Comment by gsdias** [comment]
Did everything again for the 10th time and it works now. Tks

**Comment by cbrevik** [comment]
10th times the lucky charm I guess?
