### ISSUE TITLE
How to use one tracker instance in different files

### ISSUE THREAD

**Issue by em222iv** [idehub/react-native-google-analytics-bridge#114]
**example:**
**index.js**
import { GoogleAnalyticsTracker } from 'react-native-google-analytics-bridge';
let tracker = new GoogleAnalyticsTracker('UA-----');
tracker.trackScreenView('index');

**other-page.js**
tracker.setUser('user-id')

**Comment by cbrevik** [comment]
Hi @em222iv, 

Please look through the issues before posting a new one, this has already been answered in #104

**Comment by em222iv** [comment]
My bad, thanks!
