### ISSUE TITLE
Enabling iTunes Store tracking

### ISSUE THREAD

**Issue by DVassilev** [idehub/react-native-google-analytics-bridge#115]
Is it possible to enable the option to track referrals to iTunes Store? I saw it required enabling IDFA and some other things.

**Comment by cbrevik** [comment]
Hi, this goes under campaigns doesn't it? See #30

I sadly don't have a good answer here, but it should be possible.

**Comment by cbrevik** [comment]
See https://github.com/idehub/react-native-google-analytics-bridge/issues/30#issuecomment-310279389. Closing this issue.
