### ISSUE TITLE
Issue with Google Tag Manager

### ISSUE THREAD

**Issue by gyzerok** [idehub/react-native-google-analytics-bridge#116]
Hello there!

First of all thank for such a lovely package!

I am trying to set up it to work with Google Tag Manager, but it seems that no events get through. I've followed installation instructions for Android form Tag Manager itself and this package as well. All the methods seem to resolve to successful Promises, but there are nothing in analytics.

Are there some known issues I should be aware of? Do you have any ideas what might me the root cause of the problem?

**Comment by cbrevik** [comment]
Hi @gyzerok,

I'd recommend in any case to setup logging in order to debug. Check out the wiki for that. 

Other than that I'd have to ask if you've verified that your GTM account/container is setup correctly, and connected to your GA account?

**Comment by gyzerok** [comment]
@cbrevik thanks for your response!

It seems like container set up is good, because if I pass incorrect id then the whole thing fail, but if I pass correct one everything is fine.

When using `logcat` I can see following in my logs.
```
02-22 11:56:52.814 E/GoogleTagManager( 2934): Invalid macro: _gtm.loadEventEnabled
```

**Comment by cbrevik** [comment]
I am unsure if I've understood the problem correctly.

Did you do a separate installation of GTM (Android form Tag Manager you said) in the app? Other than just installing this module?

Have you tried setting up some values and retrieve them from the container?

**Comment by gyzerok** [comment]
Ah, sorry. Let me try to explain it better.

I was following [these instructions](https://developers.google.com/tag-manager/android/v4/) to add proper permissions and container binary into the application.

Then I am using your plugin in the following way
```js
GoogleTagManager
  .openContainerWithId('GTM-XXX111Q')
  .then(() =>
    GoogleTagManager.pushDataLayerEvent({
      event: 'event',
      action: 'hello',
    }),
  )
  .then(val => console.log(val)); // prints "true"
```

If I would change container id to just some weird string, then I will receive an error that it doesn't exists, which, I guess, mean that plugin is able to find installed container.

The problem is that no event get through to the google tag manager. It looks like even thought there are no error the event do not get sent.

Meanwhile each time I do try send new event I do see following error in `logcat`.

```
02-22 11:56:52.814 E/GoogleTagManager( 2934): Invalid macro: _gtm.loadEventEnabled
```

**Comment by gyzerok** [comment]
@cbrevik not sure if you seen the message without mention. Sorry for pinging you twice otherwise.

**Comment by cbrevik** [comment]
Sorry @gyzerok, the previous week(end) has been busy, forgot about this issue.

From googling, it doesn't seem like `Invalid macro: _gtm.loadEventEnabled` is that big of an issue. So I'm not sure that is the problem. I haven't got the opportunity to test if I get that error too though, at the moment.

Have you attempted a simple web-integration on a test page, just to see that if GTM works there? It'd be good to rule out an issue with GTM not properly connected to GA or something.

**Comment by uc-asa** [comment]
I have the same issue. Any update?
