### ISSUE TITLE
Recorded app version and where to find the Label, Key values

### ISSUE THREAD

**Issue by nicolabortignon** [idehub/react-native-google-analytics-bridge#118]
First and foremost,
thank you for the great work on this brige, the installation was flowless and I got my up emitting event in less than 10 minutes.

I have 2 questions (probably quite trivial):

1- the app version that is tracked on Anlytics is by default 1.0. How can I change it? IS that a value picked up from XCode field ? if yes, where is the Android setting?

2- I dispatch events in this way:

    trackScreenView('Product Screen', {label: 'id', value: this.props.id})

So ideally, every time the user gets to the Product Screen view, I know the id of the product.
Unfortunately I cannot find that dimension on analytics.

Any idea? 

Thank you again
Nicola

**Comment by cbrevik** [comment]
Hi @nicolabortignon 

1. The app versions, are as far as I know, picked up from the `Info.plist` for iOS. And in the `build.gradle` for Android. Basically the same version fields you mutate for releases in store.

2. The [`trackScreenView`](https://github.com/idehub/react-native-google-analytics-bridge#trackscreenviewscreenname) does not have labels. You want to use the [`trackEvent`](https://github.com/idehub/react-native-google-analytics-bridge#trackeventcategory-action-optionalvalues).
