### ISSUE TITLE
How to set user traits?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [idehub/react-native-google-analytics-bridge#119]
Hi,

Usually with these libs there's an identify() method where you pass not only a userId, but also a dictionary of traits for that user.

I see setUser() just takes a userID.

How do I send user traits?

**Comment by cbrevik** [comment]
Hi @GeoffreyPlitt. 

I don't know of any methods that lets you send user traits. According to the docs there is just userId: https://developers.google.com/analytics/devguides/collection/ios/v3/user-id

As far as I know, analytics of this sort shouldn't identify single users. It is more used for user "trends". If several users have a similar "trait" which you want to filter on, I'd suggest using `trackEvent` or other metrics.
