### ISSUE TITLE
libz.tbd and ibsqlite3.0.tbd (No such file or directory)

### ISSUE THREAD

**Issue by pgonzalez-santiago** [idehub/react-native-google-analytics-bridge#123]
Hello all, I just installed the library and follow all the steps but I'm getting these errors.

`error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk/usr/lib/libsqlite3.0.tbd (No such file or directory)`

`error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk/usr/lib/libz.tbd (No such file or directory)`

In `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk/usr/lib/` there are no .tbd files, only .dylib

Any idea? Thank you.

I am using RN 0.42.0 and Xcode 8.2.1

**Comment by austinkettner** [comment]
Same here.

**Comment by cbrevik** [comment]
Hi. I'm not sure what the problem here is sorry. Those libs should be shipped in the framework with Xcode, and is not directly related to this module.

**Comment by austinkettner** [comment]
It only occurs when this is linked in. Do you not experience this at all @cbrevik I find it hard to imagine it's not related to some part of this module given unlinking this module resolves the issue, but can further test.

**Comment by cbrevik** [comment]
Sorry, maybe I'm misunderstanding. You have linked the necessary libraries in your Xcode-project right? As per the [manual installation step 5](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Manual-installation#manual-installation-ios)?

**Comment by austinkettner** [comment]
@cbrevik Missed one of these steps, so all good now! Thanks
