### ISSUE TITLE
[Question] The device UUID, device model, viewport size, OS version etc are not listed on Google Analytics dashboard. 

### ISSUE THREAD

**Issue by tinajohnson** [idehub/react-native-google-analytics-bridge#128]
App version and Screen name are the only columns I get on the dashboard. How can I get the other details?

**Comment by cbrevik** [comment]
Hi @tinajohnson, this is a GA-interface specific question, and not really within the scope of this repository. I recommend learning the interface better, specifically checking out secondary dimensions.
