### ISSUE TITLE
cannot read property 'trackScreenView' of undefined

### ISSUE THREAD

**Issue by retailos** [idehub/react-native-google-analytics-bridge#132]
React-Native: 0.42.3
react-native-google-analytics-bridge: 5.0.1

Hi,

I am using the module on both iOS and Android. iOS works but Android always throws an error whenever I attempt to track anything.

My code is simply

```
import { GoogleAnalyticsTracker } from 'react-native-google-analytics-bridge'

const tracker = new GoogleAnalyticsTracker('UA-XXXXXXXX-1')
tracker.trackScreenView('test')
```

I have installed all required SDKs/Tools through Android Studio and ran "rnpm link react-native-google-analytics-bridge". Regardless though _NativeBridges.GoogleAnalyticsBridge remains undefined. I have cleaned and rebuilt the project with no results. I have checked through the readme on the repo and cannot see any missed steps, could you recommend anything else?

**Comment by cbrevik** [comment]
Hi @retailos, this question comes up all the time, and most of the time the module has been incorrectly linked. See [manual installation](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Manual-installation) for details on how things should have been linked. By the way `rnpm` is deprecated, I recommend using `react-native link`.

**Comment by retailos** [comment]
@cbrevik Thanks for the tip I have checked through the manual installation again and can see the original rnpm link did not complete the MainApplication.java step. On completion it is all working.
