### ISSUE TITLE
No hit on Google Analytics but no error when executing the code

### ISSUE THREAD

**Issue by podybman** [idehub/react-native-google-analytics-bridge#134]
Hi,

I've implemented RNGAB: 
- on the native code for Android
- on the React Part as follow: 
`render () {
    GoogleAnalyticsSettings.setDispatchInterval(2)
    GoogleAnalyticsSettings.setDryRun(true)

    let tracker = new GoogleAnalyticsTracker('UA-XXYYXXYY-1')
    console.log('RootContainer', tracker)

    tracker.setTrackUncaughtExceptions(true);

    tracker.trackScreenView('Home')
    tracker.trackEvent('testcategory', 'testaction')
    tracker.setTrackUncaughtExceptions(true)
    return (
      <View style={styles.applicationView}>
        <StatusBar barStyle='light-content' />
        {this.renderRootContent()}
      </View>
    )
  }`

My RootContent is shown without any problem, I don't have any error from GA but I still don't see any hit on GA. 
Did anybody had the same problem at some point?

**Comment by cbrevik** [comment]
Hi @podybman, as it says [in the README](https://github.com/idehub/react-native-google-analytics-bridge#setdryrunenabled); when `dryRun` is set to `true`, no hits are sent to GA:

> When enabled the native library prevents any data from being sent to Google Analytics. This allows you to test or debug the implementation, without your test data appearing in your Google Analytics reports.

**Comment by podybman** [comment]
I've reached this level of dumb apparently. 

Thanks ;)
