### ISSUE TITLE
Setting up Google Analytics property?

### ISSUE THREAD

**Issue by praveenperera** [idehub/react-native-google-analytics-bridge#136]
I'm trying to figure out how to setup a google analytics property to use this package. Am i supposed to set it up as a website? Because when i try to set it up as a mobile app it takes me to firebase and then does not give me a tracking id (UA.....)

**Comment by jeanregisser** [comment]
Looks like we're supposed to select "Website" when creating the new property.
See https://support.google.com/analytics/answer/2587086?hl=en

**Comment by cooperka** [comment]
I had a hard time setting this up recently; it looks like Google is trying to deprecate regular Analytics in favor of Firebase Analytics. You can use this library instead: https://github.com/evollu/react-native-firebase-analytics. Working great for me with latest React Native on Android and iOS.

**Comment by praveenperera** [comment]
@cooperka I ended up going with that package as well
