### ISSUE TITLE
Error with Google Tag Manager.

### ISSUE THREAD

**Issue by krailler** [idehub/react-native-google-analytics-bridge#138]
When i push data to dataPlayer i get following error in logcat:

```GAv4    : Discarding hit. Missing hit type parameter: a=1955761582,tid=_GTM_DEFAULT_TRACKER_```

Any help? In iOS run works correctly.

**Comment by cbrevik** [comment]
This is not enough information to debug this.

Code sample, or optimally a test project is needed.
