### ISSUE TITLE
trackScreenView() seems not working

### ISSUE THREAD

**Issue by changminc** [idehub/react-native-google-analytics-bridge#14]
I am using React Native 0.20. I don't know my problem is related to the version of RN. 
My application consists of this structure:

    index.android.js --> A.js  ---> B.js (main scene initially rendered)
    index.android.js --> A.js  ---> C.js                   
    index.android.js --> A.js  ---> D.js

So,   B/C/D scenes are located under the navigator of A.js
I put `trackScreenView('B')` / `trackScreenView('C')` / `trackScreenView('D')` into B / C /D, respectively.
In GoogleAnalytics page, however, the tracker shows only B scene... even though I changed the scenes and waited for minutes. 

Please drop a comment to figure this out.

**Comment by cbrevik** [comment]
Hi @changminc!

Is this on iOS or Android? Also have you debugged the JS and native code and seen if `trackScreenView` gets called all three times?

**Comment by changminc** [comment]
It happens in iOS and Android both. I'm sorry I am not good at debugging React Native with Chrome or Xcode. The only thing I know for debugging is using `console.log()`. Is there a way to confirm that a function `GoogleAnalytics.trackScreenView('B')` is called?
I checked it at  of Google Analytics in real time.

**Comment by cbrevik** [comment]
Well, if you are running on the iOS emulator, you can connect to the Chrome-debugger by pressing `control + ⌘ + z` while the app is running, and choosing "Debug in Chrome".

This should open up a tab in Chrome, and you can click `⌘ + option + i` to open up the devtools. If you then go to the `Sources`-tab in the devtools, find the `react-native-google-analytics-birdge` folder in the `node_modules` folder, and open the `index.js` file.

Here you should be able to click on the line numbers in the file to set break points. Find the line where `GoogleAnalyticsBridge.trackScreenView(screenName);` is called (line 11 probably), and set a break point (blue arrow-line).

You can then try to navigate in the app, and the devtools should jump in where the break point is set when the method is called. To resume normal app running after a break point is hit you can do this with the Play-button in the top right of the Sources-tab in devtools.

Verify if the `trackScreenView` is called at all when navigating to A, B, C, etc.

[More info about debugging React Native](https://facebook.github.io/react-native/docs/debugging.html). 
[General info about Chrome debugging in Sources](https://developers.google.com/web/tools/chrome-devtools/debug/breakpoints/)

**Comment by changminc** [comment]
Thanks a lot, @cbrevik !!  
Thanks to your kind description, I could confirm that my app preloads the all scenes(A, B, C). 
Thus, `GoogleAnalytics.trackScreenView('A')`, `GoogleAnalytics.trackScreenView('B')`, `GoogleAnalytics.trackScreenView('C')`, they all are loaded at initial running. 
However, each trackScreen function was not called when I changed the scenes among A, B, C.

I think my app's structure is kind of typical. Should I change it?

**Comment by changminc** [comment]
I solved the problem. 
It was caused from the position of `trackScreenView()`. 
Firstly, I called the function before declaring a scene module like below.

    var React = require('react-native');
    var GoogleAnalytics = require('react-native-google-analytics-bridge');
    GoogleAnalytics.trackScreenView('A');
    ...
    class Scene_A extends React.Component {
    ...
    }

Now, I moved the `GoogleAnalytics.trackScreenView('A');` into declaring a class. 

    var React = require('react-native');
    var GoogleAnalytics = require('react-native-google-analytics-bridge');
    ...
    class Scene_A extends React.Component {
        constructor(props) {
          super(props);
          GoogleAnalytics.trackScreenView('A');
        }
    ...
    }

I confirmed it called whenever I changed scenes, and I could see it working correctly in real-time page of Google Analytics, too.

I hope that other developers do not make a mistake as I did. 
@cbrevik , your advice was very helpful. Thank you very much.

**Comment by cbrevik** [comment]
Nice @changminc! Happy to hear it worked out for you!
