### ISSUE TITLE
libRCTGoogleAnalyticsBridge.a missing - cannot install

### ISSUE THREAD

**Issue by linnett** [idehub/react-native-google-analytics-bridge#141]
Point 4 of the documentation states: `Go to RCTGoogleAnalyticsBridge.xcodeproj project properties ➜ "Build Phases" ➜ "Link Binary With Libraries" and add libRCTGoogleAnalyticsBridge.a from the linked project in the node_modules/react-native-google-analytics-bridge/ios path.`

I am unable to find the libRCTGoogleAnalyticsBridge.a in the node_modules/react-native-google-analytics-bridge/ios path. 

I've previously tried linking using `$ react-native link react-native-google-analytics-bridge` but this causes the following error when trying to track the screen view: `undefined is not an object (evaluating '_NativeBridges.GoogleAnalyticsBridge.trackScreenView')`.

EDIT: I think I understand point 4 now. It appears you are saying "Click on <your project> in the side bar ➜ Click on Build Phases ➜ Link Binary With Libraries, then add libRCTGoogleAnalyticsBridge.a"? 
If so, please close this 👍

**Comment by flunder** [comment]
I had those installation problem a while now, the example shows this setup which has seems to have stopped it from complaining.

<img width="1293" alt="screen shot 2017-06-12 at 15 24 55" src="https://user-images.githubusercontent.com/91437/27038598-614f1da8-4f83-11e7-8a6d-78ecebac7fe4.png">

<img width="1293" alt="screen shot 2017-06-12 at 15 25 09" src="https://user-images.githubusercontent.com/91437/27038599-616268e0-4f83-11e7-82e7-8806c7b24832.png">

**Comment by linnett** [comment]
Yeah it appears to be working for me now, but the documentation certainly isn't clear enough

**Comment by cbrevik** [comment]
Sorry, the wiki was updated wrongly by someone. I really recommend doing this part with `react-native link` though.

**Comment by cbrevik** [comment]
Wiki has been updated, so closing.
