### ISSUE TITLE
no resource found

### ISSUE THREAD

**Issue by vijaemanlapaz** [idehub/react-native-google-analytics-bridge#148]
http://imgur.com/a/v7V0D

how can i fix this?

**Comment by cbrevik** [comment]
Unsure @vijaemanlapaz. Not a lot to go on here. Might be an issue with folder name length on Windows? What if you place the project in a folder closer to `C:\`?

**Comment by chris-garrett** [comment]
I was having this issue on windows and moving my project resolved these errors.
