### ISSUE TITLE
Is Enhanced Ecommerce Tracking supported?How to add product impression tracking?

### ISSUE THREAD

**Issue by bpt2410** [idehub/react-native-google-analytics-bridge#150]
I want to add product impression tracking as https://developers.google.com/analytics/devguides/collection/ios/v3/enhanced-ecommerce
How to do it?
Please help me, thanks a lot.

**Comment by cbrevik** [comment]
Hi @bpt2410. 

We use enhanced ecommerce tracking of purchases. At the moment impressions/checkout isn't supported though. 

I have it on the roadmap, but haven't devoted any time to it: https://github.com/idehub/react-native-google-analytics-bridge/wiki/Roadmap

If you (or anyone else) would like to contribute here, I'd be more than happy to review code and help out where possible. 

I think how we've done it for purchase tracking is a good guide for how to implement it. Just look at how it was done [on the JS side](https://github.com/idehub/react-native-google-analytics-bridge/blob/a3bc743f2675df6220150856c03f54bb09d0fc4b/src/GoogleAnalyticsTracker.js#L116), and for [iOS](https://github.com/idehub/react-native-google-analytics-bridge/blob/a3bc743f2675df6220150856c03f54bb09d0fc4b/ios/RCTGoogleAnalyticsBridge/RCTGoogleAnalyticsBridge/RCTGoogleAnalyticsBridge.m#L100) and [Android](https://github.com/idehub/react-native-google-analytics-bridge/blob/a3bc743f2675df6220150856c03f54bb09d0fc4b/android/src/main/java/com/idehub/GoogleAnalyticsBridge/GoogleAnalyticsBridge.java#L122), and then follow the [iOS docs](https://developers.google.com/analytics/devguides/collection/ios/v3/enhanced-ecommerce#measuring-impressions) and [Android docs](https://developers.google.com/analytics/devguides/collection/android/v4/enhanced-ecommerce#measuring-impressions) for implementation details.

**Comment by bpt2410** [comment]
Hi @cbrevik
I got it, thanks for your support
