### ISSUE TITLE
Will this work with Expo?

### ISSUE THREAD

**Issue by rshellborn** [idehub/react-native-google-analytics-bridge#152]
Currently have an Expo app, but I keep getting an error:

TypeError: undefined is not an object (evaluating '_NativeBridges.GoogleAnalyticsBridge.trackScreenView')

I can't do manual install because I would have to detach.

**Comment by cbrevik** [comment]
Hi @rshellborn. 
Probably not, Expo only works with modules made for Expo (i.e. part of their offering). So as you say, to make use of custom modules from the rest of the RN ecosystem you will have to detach.
