### ISSUE TITLE
Does this module works in simulator ?

### ISSUE THREAD

**Issue by rocwangv** [idehub/react-native-google-analytics-bridge#153]
Thanks for providing this module.
I use it debug in ios simulator and code works normally , But Google Analytics has no data from 10:00am to now .....

My code like this:
**BaseComponent**
 >This is a base component and  all other component extends this.
```
import React, { Component } from 'react';
import { View } from 'react-native';
import { GoogleAnalyticsTracker } from 'react-native-google-analytics-bridge';
let tracker = new GoogleAnalyticsTracker('UA-1*****4-1');

export default class BaseComponent extends Component {
    constructor(props) {
        super(props);
        tracker.trackScreenView(this.constructor.name);
    }

    render() {
        return <View />;
    }
}
``` 

I debugged it in my Chrome and code ran `trackScreenView` in this module's `GoogleAnalyticsTracker.js` 56 line .

Please help me , this question confused me all day!

**Comment by rocwangv** [comment]
I test my app in real device , doesn't works too

**Comment by jdrouet** [comment]
I have the same issue

**Comment by cbrevik** [comment]
Hi, it should work fine on both simulator and device. Most of the time errors like this is from wrong installation or use.

Recommend:
1. Review the manual installation to see if linked etc is set up in your projects correctly: https://github.com/idehub/react-native-google-analytics-bridge/wiki/Manual-installation

2. Do some logging: https://github.com/idehub/react-native-google-analytics-bridge/wiki/Troubleshooting#google-analytics-logging

Also make sure [`dryRun`](https://github.com/idehub/react-native-google-analytics-bridge#setdryrunenabled) is not set to true.

**Comment by rocwangv** [comment]
@cbrevik Thank you man , When I set dryRun to false , it works.
Before,as  [USAGE](https://github.com/idehub/react-native-google-analytics-bridge#usage) says ,I set dryRun to true.
