### ISSUE TITLE
duplicate entry: com/google/android/gms/internal/zzbi.class

### ISSUE THREAD

**Issue by fedeerbes** [idehub/react-native-google-analytics-bridge#155]
Hi guys, i have a problem with my app, is a expo detached proyect

![captura de pantalla 2017-08-01 a las 6 40 46 p m](https://user-images.githubusercontent.com/18606335/28848375-17e1176a-76e9-11e7-9830-3cf0e124b24f.png)

when i run the proyect with Android Studio

I'm using v5.2.1 of react-native-google-analytics-bridge, any ideas?
BTW i read the manual installation guide and i have it. 

Thanks

**Comment by cbrevik** [comment]
You probably have another module using a conflicting Play Services version https://github.com/idehub/react-native-google-analytics-bridge/wiki/Troubleshooting#android-build-problem

**Comment by fedeerbes** [comment]
Thankz Christian!  I'll check that

El 2 ago. 2017 1:03, "Christian Brevik" <notifications@github.com> escribió:

You probably have another module using a conflicting Play Services version
https://github.com/idehub/react-native-google-analytics-
bridge/wiki/Troubleshooting#android-build-problem

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/idehub/react-native-google-analytics-bridge/issues/155#issuecomment-319561441>,
or mute the thread
