### ISSUE TITLE
Session control api not available

### ISSUE THREAD

**Issue by rathanDev** [idehub/react-native-google-analytics-bridge#157]
Session control (manually creating and invalidating google analytics sessions) have not been developed.
Session control reference in anlaytics.js -https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#session

**Comment by cbrevik** [comment]
PR is welcome. That's the wrong docs btw, this is the correct:
* iOS: https://developers.google.com/analytics/devguides/collection/ios/v3/sessions#manual
* Android: https://developers.google.com/analytics/devguides/collection/android/v4/sessions#manual

**Comment by rathanDev** [comment]
Hi, Thank you very much for the reply. I referred this readme /
documentation https://github.com/idehub/react-native-google-analytics-bridge.
My concern is that I couldn't find any methods for session control.

**Comment by cbrevik** [comment]
Published in `5.3.0`
