### ISSUE TITLE
support create-react-native-app ?

### ISSUE THREAD

**Issue by coderafei** [idehub/react-native-google-analytics-bridge#158]
will support create-react-native-app?

**Comment by cbrevik** [comment]
As far as I know `create-react-native-app` creates an Expo-app. So the answer is no.

There's been an uptick in Expo-related questions lately https://github.com/idehub/react-native-google-analytics-bridge/issues/154#issuecomment-318976520, perhaps I should add a note in the README.

**Comment by cbrevik** [comment]
Closing with README update: https://github.com/idehub/react-native-google-analytics-bridge/commit/915ae33b5a107d27d5562666a3c1cb04f3f0c805
