### ISSUE TITLE
Google Analytics is not receiving data

### ISSUE THREAD

**Issue by diegoncalves203** [idehub/react-native-google-analytics-bridge#161]
Hi,

I'm trying to hit GA but isn't working

import {
  GoogleAnalyticsTracker,
  GoogleTagManager,
  GoogleAnalyticsSettings
} from "react-native-google-analytics-bridge";

const tracker = 'UA-XXXXXXXX-X';
let instance = null;

class GAService {
  GAService() {
    if (!instance) {
      instance = this;
    }

    return instance;
  }

  getTracker() {
    try {
      GoogleAnalyticsSettings.setDispatchInterval(30);
      GoogleAnalyticsSettings.setDryRun(false);

      return new GoogleAnalyticsTracker(tracker);
    } catch (error) {
      console.log(error);
    }
  }

  setTrackerScreen(screenName) {
    try {
      this.getTracker().trackScreenView(screenName);
    } catch (error) {
      console.log(error);
    }
  }

  setTrackerEvent(category, action) {
    try {
      this.getTracker().trackEvent(category, action);
    } catch (error) {
      console.log(error);
    }
  }
}

let service = new GAService();

export default service;

What i've done wrong?

**Comment by nolan-m** [comment]
I was having the same problem.  I finally figured out how to get it working.

For some reason you need to initialize the GoogleAnalyticsTracker with the `customDimensionsFieldsIndexMap` parameter.  The docs say this is optional, but there must be a bug somewhere not defaulting this value.  I just used an empty object since the docs show it should default to that.

```
let tracker1 = new GoogleAnalyticsTracker('UA-104920000-1', {});
```

**Comment by jacobjuul** [comment]
@nolan-m still doesn't work for me

**Comment by cbrevik** [comment]
If you've set `setDryRun` to `true`, then GA will not receive any data.

**Comment by jacobjuul** [comment]
Dryrun is set to true

**Comment by cbrevik** [comment]
Then you should set it to `false` (or do not set it at all) if you want to receive data :)

**Comment by jacobjuul** [comment]
Sorry I meant I set it to false

**Comment by cbrevik** [comment]
Alright, cool! I'm considering this issue resolved then. 

I'm linking this comment for people checking back later: https://github.com/idehub/react-native-google-analytics-bridge/issues/164#issuecomment-328288270

Sometimes Google Analytics itself might be slow in receiving data it seems.

**Comment by jacobjuul** [comment]
@cbrevik, this is not resolved for me, I meant, when I set it to false, it still doesn't send any data.

**Comment by jacobjuul** [comment]
I can step into the

**Comment by cbrevik** [comment]
Then I recommend you enable logging to see if it actually sends anything; https://github.com/idehub/react-native-google-analytics-bridge/wiki/Troubleshooting#google-analytics-logging

If the trace says it is sending hits, then there's nothing wrong with this lib. In that case it is probably the wrong UA-ID, something to do with dispatch time, or similar.

**Comment by jacobjuul** [comment]
```
parameters =     {
        "&_crc" = 0;
        "&_s" = 18;
        "&_u" = ".nK9L";
        "&_v" = "mi3.1.7";
        "&a" = 776343937;
        "&aid" = "enterprise.xx.staging";
        "&an" = nuke;
        "&av" = "2.01";
        "&cd" = "tools";
        "&cid" = "8e239739-f805-4b9c-9de0-999a451ca15b";
        "&dm" = "x86_64";
        "&ds" = app;
        "&sr" = 750x1334;
        "&t" = screenview;
        "&tid" = "UA-1XXXXXX6-2";
        "&ul" = en;
        "&v" = 1;
        "&z" = 13442048977687679031;
        gaiVersion = "3.17";
    };
    timestamp = "2017-09-11 06:27:28 +0000";
```

But there is no screenview data in the GA dashboard. It only shows connected users

**Comment by oriharel** [comment]
@jacobjuul Is this thing resolved for you? I'm having the same issue

**Comment by luongs3** [comment]
@jacobjuul  @oriharel me too, i  get the exactly same issue.

**Comment by luongs3** [comment]
@cbrevik what do you think

**Comment by luongs3** [comment]
i got this in my logcat
```
01-25 13:14:03.400 11134 12018 W GAv4    : AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions.
01-25 13:14:03.403 11134 12018 W GAv4    : CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
01-25 13:14:03.404 11134 12018 W GAv4    : AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
```

**Comment by luongs3** [comment]
after fix error AnalyticsReceiver is not registered. This's my logcat:
```
01-25 14:04:29.640 12740 12851 D GAv4    : Hit delivery requested: ht=1516863869610, _s=26, _v=ma11.0.20, a=2102157777, aid=com.vibloapp, an=Viblo, av=1.0, cd=/posts/4dbZNgJ8lYM, cid=8e51e27b-57ca-4b7b-9b2e-6f18e428ab34, sr=1440x2392, t=screenview, tid=UA-88817199-3, ul=en-us, v=1
01-25 14:04:29.685 12740 12851 D GAv4    : Hit sent to the device AnalyticsService for delivery
01-25 14:04:59.390  1240  1290 D hwcomposer: hw_composer sent 3565 syncs in 60s
```

**Comment by cbrevik** [comment]
Try registering `AnalyticsService` & `AnalyticsReceiver` in your apps `AndroidManifest.xml`:
https://developers.google.com/analytics/devguides/collection/android/v4/dispatch#background

**Comment by luongs3** [comment]
unfortunately, it just resolves the error about AnalyticsService, not the error we are talking about
> But there is no screenview data in the GA dashboard. It only shows connected users

**Comment by luongs3** [comment]
Hey guys, i knew the reason. It's because you need to create separated View for mobile application.
When you create new account, you must select between Website and Mobile Application. If you want to show Screen name, you must choose mobile application.
Except data about screen name vs page view, and some special data in mobile or website (site content), other data will be combined automatically by google (as users, sessions).
We don't have any problem with code.

**Comment by cbrevik** [comment]
Aha, yes I've given a walkthrough on that before: https://github.com/idehub/react-native-google-analytics-bridge/issues/208#issuecomment-358583557

Setting mobile view as default view should help.

I should probably add that to the README or something
