### ISSUE TITLE
How to debug not receiving data

### ISSUE THREAD

**Issue by scottwilson312** [idehub/react-native-google-analytics-bridge#164]
I have this code inside my componentDidMount

        let tracker = new GoogleAnalyticsTracker('UA-xxxx-1', {});
        GoogleAnalyticsSettings.setDryRun(false);
        GoogleAnalyticsSettings.setDispatchInterval(3);
        console.log("TRACKING")
        tracker.setSamplingRate(100);
        tracker.trackScreenView('Folder')
        tracker.trackEvent('view', 'folder');

I am not seeing anything received in google analytics. I verified my ID is correct. What is the best way to debug? I'm not seeing any errors in logcat or anything

**Comment by scottwilson312** [comment]
Okay, I'm seeing this warning in logcat

08-21 14:46:03.848 W/GAv4    (25467): AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
08-21 14:46:59.051 I/GAv4    (25590): Google Analytics 10.2.98 is starting up. To enable debug logging on a device run:
08-21 14:46:59.051 I/GAv4    (25590):   adb shell setprop log.tag.GAv4 DEBUG
08-21 14:46:59.051 I/GAv4    (25590):   adb logcat -s GAv4
08-21 14:46:59.065 W/GAv4    (25590): AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions.

**Comment by scottwilson312** [comment]
I added the receiver to my manifest file and got rid of the warnings. Now it looks like hits are being sent, but I'm still not seeing anything in the analytics dashboard. Has anyone experienced this?

08-21 15:15:00.730 D/GAv4    (30066): setLocalDispatchPeriod (sec): 3
08-21 15:15:00.747 D/GAv4    (30066): Hit delivery requested: ht=1503346500731, _s=6, _v=ma10.2.98, a=1766700456, aid=com.woz.tagamate, an=TagAMate, av=1.3, cd=Folder, cid=e6f4319f-341c-4773-ae35-62756f840cab, sf=100.0, sr=1080x1776, t=screenview, tid=UA-105033496-1, ul=en-us, v=1
08-21 15:15:00.756 D/GAv4    (30066): Hit delivery requested: ht=1503346500732, _s=7, _v=ma10.2.98, a=1766700457, aid=com.woz.tagamate, an=TagAMate, av=1.3, cd=Folder, cid=e6f4319f-341c-4773-ae35-62756f840cab, ea=folder, ec=view, sf=100.0, sr=1080x1776, t=event, tid=UA-105033496-1, ul=en-us, v=1
08-21 15:15:00.829 D/GAv4    (30066): Hit sent to the device AnalyticsService for delivery
08-21 15:15:00.844 D/GAv4    (30066): Hit sent to the device AnalyticsService for delivery

**Comment by cbrevik** [comment]
Is this still a problem @scottwilson312?

Normally it's a dispatch interval issue, but looks like yours is low. The other thing is that `dryRun` must not be set to `true`.

**Comment by scottwilson312** [comment]
It was just Google Analytics being annoying - there was nothing wrong with this code. I had created my account two days prior and nothing was showing up. I switched the ID to an old account of mine and everything was working fine

**Comment by cbrevik** [comment]
Alright good to hear, glad it worked out for you! Thanks for the notice and closing the issue.

**Comment by Coobers** [comment]
I found the problem with new accounts.
In order to activate it in EU go to Account Settings, scroll to  Data Processing Amendment  and accept.
Data started pouring instantly ;)

**Comment by martinbydefault** [comment]
@Coobers , I was experiencing the same problem and that solved it, thanks!  
@cbrevik I know this is not exactly related to this repository because is a "google problem" but I think it would help others if a note is added to the wiki or to the README giving a warning about this.  
In my case for example, I spent a lot of time debugging the configuration and installation and after some hours of that and nothing else to try, I discovered this issue and coobers solution.   
What do you think?   
If you prefer I can write it and send in a PR (in that case, and if you agree, just tell me where it would be more suitable to be added).
