### ISSUE TITLE
Compatibility with background dispatching (without Google Play Services)

### ISSUE THREAD

**Issue by grsmvg** [idehub/react-native-google-analytics-bridge#166]
It looks like this plugin is not compatible with background dispatching (without Google Play Services), explained here:

https://developers.google.com/analytics/devguides/collection/android/v4/dispatch#background

Is that correct? How easy is it to fix this?

**Comment by cbrevik** [comment]
It says right in your link there how to fix it by adding a `WAKE_LOCK` permission request + register Receiver/Service in your app project `AndroidManifest.xml` file.

This module does not add this by default, and that is on purpose. I don't want to add extra permissions requests that developers might not need.

**Comment by grsmvg** [comment]
Yes, I already did this 😉  Turned out Analytics was already recording my actions for an hour, but it just didn't show up in realtime. But in reports it looks good 👍
