### ISSUE TITLE
RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by NirBenya** [idehub/react-native-google-analytics-bridge#167]
followed the docs (using RN 0.46), but get this error.
any thoughts ?

I'm detached from expo btw.
![screen shot 2017-09-11 at 11 35 22 am](https://user-images.githubusercontent.com/15313208/30265629-5ef48daa-96e5-11e7-9bd5-7e67315b5161.png)

**Comment by cbrevik** [comment]
Most likely not installed node modules
