### ISSUE TITLE
Does not build with buildToolsVersion 25 on Android

### ISSUE THREAD

**Issue by mo-solnet** [idehub/react-native-google-analytics-bridge#170]
The latest Android Studio and Gradle require `buildToolsVersion 25` and this library does not build with that version.

**Scenario**: A project is using this library as a dependency. The project updates to latest RN (0.47.2) as well as Android Studio 2.2.3. This library will prevent building the project because the `buildToolsVersion` is too low.

**Comment by cbrevik** [comment]
Hi @mo-solnet.

Are you sure the latest Android Studio requires `buildToolsVersion 25`?

Creating a new React Native project I find that it still depends on `23.0.1`:
```
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
```

I'm vary of upgrading this unless there is a real need for it.

**Comment by RobertSheaO** [comment]
@mo-solnet You can force your dependencies to use whatever SDK you'd like. There's no guarantee it'll work, but I'm currently using version 25 with no problem. Here's how you'd do it:

You need store your `compileSdkVersion` and `buildToolsVersion` into a variable you can use in both build.gradle files. Then edit your `android/build.gradle` like so. It's the `subprojects` portion that does the magic.

###### android/build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

ext {
    compileSdkVersion = 25
    buildToolsVersion = "25.0.1"
}

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

Then use the two variables you setup at the top as part of `ext` inside your `android/app/build.gradle` file.

###### android/app/build.gradle
```
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
}
```

**Comment by maartenvandillen** [comment]
or like this: https://github.com/oblador/react-native-keychain/issues/68#issuecomment-304836725

**Comment by RobertSheaO** [comment]
@maartenvandillen, That's the exact same solution, aside from setting a global variable for `compileSdkVersion` and `buildToolsVersion` to prevent version drift.

**Comment by maartenvandillen** [comment]
Yes I know, but I came here specifically to post the comment and then I saw yours and thought I might as well post it anyway to indicate that this problem happens to other libs as well.

**Comment by RobertSheaO** [comment]
Ah, okay. I was confused, but that makes sense.
