### ISSUE TITLE
Container not loading

### ISSUE THREAD

**Issue by Hashan1100** [idehub/react-native-google-analytics-bridge#173]
Hi,

I can't load the container. I get this error.

```
Error: Failed to open container. Does container with id GTM-XXXXXXX exist?
    at createErrorFromErrorData (NativeModules.js:116)
    at NativeModules.js:79
    at MessageQueue.__invokeCallback (MessageQueue.js:290)
    at MessageQueue.js:127
    at guard (MessageQueue.js:46)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:71

```
I followed the steps correctly to implement GTM.

My code is

```
import { GoogleTagManager } from 'react-native-google-analytics-bridge';
GoogleTagManager.openContainerWithId("GTM-XXXXXXX")
    .then(() => {
        return GoogleTagManager.stringForKey("pack");
    })
    .then((pack) => {
        console.log("Pack: ", pack);
    })
    .catch((err) => {
        console.log(err);
    });

```
Please help.

**Comment by cbrevik** [comment]
Like the error says, "Does container with id GTM-XXXXXXX exist?"

Have you created a GTM account with a containerId which you send in?

**Comment by Hashan1100** [comment]
Yes I did. I actually solved the issue some what. It actually works fine when the container is legacy android. But when the container is general android with fire-base it gives above error. I need a container with a fire-base support.

**Comment by cbrevik** [comment]
I'm sorry but this library does not have support for Firebase

**Comment by Hashan1100** [comment]
But When I connect using IOS application with a IOS container with fire-base support it works fine. Only the android application has the issue. Anyway if I want to open a container in google tag manager which supports fire-base analytics (Not a legacy android container) using this library should I need additional libraries to initialize fire-base in react code.

**Comment by uc-asa** [comment]
@Hashan1100, How did you solved the issue? Actually I'm stuck with same issue, Can you help please.

**Comment by Hashan1100** [comment]
I solved the issue. When you use fire-base with GTM. You need to fire the events directly to the fire-base, Not to GTM.

**Comment by uc-asa** [comment]
I'm not using firebase, I'm just push data layer into GTM

**Comment by Hashan1100** [comment]
Did you create a container in GTM?

**Comment by uc-asa** [comment]
Yes.

**Comment by Hashan1100** [comment]
What kind of a container?

**Comment by uc-asa** [comment]
I've just created for testing with Android (legacy).

**Comment by Hashan1100** [comment]
Then Check whether you have given INTERNET permissions in manifest file.

**Comment by uc-asa** [comment]
Let me research other things, because. I have already given permission in manifest file.

**Comment by codesinghanoop** [comment]
@uc-asa did you find anything regarding this ?

**Comment by andrzejbe** [comment]
I have the same problem. I've created legacy android container (not firebase). I have INTERNET permission and with the app in production I can see the app sending *some* stats to GA. But my bug tracking regularly logs "Failed to open container" error - event though (1) container is up & available online (2) app does connect to it - at least from Android 8.x.

Whats weird is that in my bug tracking I can see JS stacktrace going back to:

```
node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:165:35value
(...) -> getCallableModule
```

..as if the problem happened *sometimes* when there's some issue on the bridge between JS & native ("Method %s does not exist on module %s")
