### ISSUE TITLE
GTM Push data layer - persisting data between pushes

### ISSUE THREAD

**Issue by bkoch31** [idehub/react-native-google-analytics-bridge#176]
Hey guys,

Plugin has been great thus far. Wanting to get into some more advanced data layer things with GoogleTagManager implementation. Having some troubles with pushing different events to GTM.

Example code:
On App resume - Firing pushDataLayer({event: event1, someMoreCustomData}) -> Firing fine on first go.

Another event we are tracking - Firing pushDataLayer({event: event2, someDifferentCustomData}) -> Fires fine

Fire first event again and some data from event2 above is persisting somehow in the GoogleTagManager object. Because this class is static I assumed all internal variables get destroyed? Maybe I m missing something. I've dumped my dictionary objects right before passing into pushDataLayer and they have the correct data. Is there a cleanse I need to run between function calls?

Cheers,

**Comment by nikolaia** [comment]
We don't use GTM in any of our projects, so don't have time or incentive to look into this. I'll leave the issue open in case someone else can assist.
