### ISSUE TITLE
Track Events Per Session?

### ISSUE THREAD

**Issue by SaraChicaD** [idehub/react-native-google-analytics-bridge#179]
Hi there, I love this library, thanks so much to all the hard work y'all!

So, I'm trying to track an `event` per `session`. I understand a "session" is automatically defined by GA as 30 mins, and that the library API allows you to control sessions, but how would you combine the two?

Any suggestions would be much appreciated. I need to track the number of times a button is pressed per session. Thanks in advance!!

**Comment by cbrevik** [comment]
Hi, I'm not sure how you'd combine two sessions. I think you need to either up the session timeout; https://support.google.com/analytics/answer/2795871?hl=en
Or find some other way to track this in GA, maybe track per user instead of session.
