### ISSUE TITLE
Feature request: Add A/B testing ability.

### ISSUE THREAD

**Issue by 5amfung** [idehub/react-native-google-analytics-bridge#18]
Having A/B testing would be nice.

**Comment by cbrevik** [comment]
Hi, I do not think the native library has inbuilt support for this.

How do you see this feature being implemented? A PR would be welcome.

**Comment by cbrevik** [comment]
On further review it seems like this can be enabled through the [TagManager](https://developers.google.com/tag-manager/ios/v3/) and Experiments in the Google Analytics web interface. 

How well this can be bridged I am not sure yet, but I will investigate further.

**Comment by evollu** [comment]
any updates on this feature?

**Comment by ericraio** [comment]
what about leveraging a similar approach as the competing react native google analytics lib?

**Comment by cbrevik** [comment]
Simple A/B-testing is now possible with the latest version (v2.0.0).

**Comment by cbrevik** [comment]
For future reference, I've also written a [short blog post](http://www.cbrevik.com/google-tag-manager-and-ab-testing-with-react-native/) on how to approach A/B-testing with this library.
