### ISSUE TITLE
Expose tracker property?

### ISSUE THREAD

**Issue by AlexMouton** [idehub/react-native-google-analytics-bridge#180]
Hi
I was looking to add some user-level attributes to my analytics.
I noticed GAITracker set value (https://github.com/idehub/react-native-google-analytics-bridge/blob/f166600215673f69aacb84b34208ca5535e0dae4/ios/RCTGoogleAnalyticsBridge/google-analytics-lib/GAITracker.h#L36) is not passed through.  
Is it reasonable to expose this?

**Comment by cbrevik** [comment]
It's not exactly unreasonable, it would make it easier for people to add custom values themselves. If the same is available on Android, a PR would be welcome.

**Comment by AlexMouton** [comment]
https://github.com/idehub/react-native-google-analytics-bridge/pull/187

**Comment by nikolaia** [comment]
Closing the issue since we have the PR
