### ISSUE TITLE
Provide support for supplying preloaded TagContainer

### ISSUE THREAD

**Issue by dmueller39** [idehub/react-native-google-analytics-bridge#181]
At the moment my team is supporting our own fork of this project where we can supply a container holder or container as an argument to the native module. This allows us to preload the container and do some queries before loading the javascript portion of the application.
We use this to drive some important features of the app, including rollback of a downloaded js bundle. This may have some benefits for "brown field" type apps that use GTM already, and would like to use the same container for the native and react native portions of the app. Is there any interest in this being added to the main fork? I wanted to explain the feature before updating everything and creating a PR.

**Comment by cbrevik** [comment]
Hi @dmueller39 

Sorry for being slow, have been extremely busy this past month. I think this sounds like something which would be perfect to add upstream. The GTM feature has not had much focus, other than necessities. I definitely see the benefit of this though!

At the moment I'm in the process of rewriting the API surface a bit in https://github.com/idehub/react-native-google-analytics-bridge/tree/typescript
But I do not think this will create any merge conflicts with changes to GTM.

If you do add this PR, I'd ask that you do it for both iOS and Android, as well as add docs.

**Comment by dmueller39** [comment]
I'm glad you mentioned the docs part, which are actually the most complicated part of the change. I was trying to write out the things you need to consider when preloading the container, and its actually pretty complicated. For instance, you need to store the launchOptions, you need to properly handle failure states, as well a group of other things that belong in the "medium to advanced" range. Furthermore, only a small fraction of users of this library are likely yo need it.
It feels like it would add a lot of complexity to the use cases of the library, without much gain.
I think its best to close this for now, but if members of the community are interested in it being added I can reopen and put together a pull request.

**Comment by cbrevik** [comment]
I'm thinking the docs does not have to be that comprehensive. A simple bullet point list is fine by me. 

There is value in adding something upstream, since more people will test and possibly add stuff on top of the feature.

**Comment by dmueller39** [comment]
Alright, I was writing out examples, and it was getting pretty hairy, I'll take another go with just a general description.

**Comment by dmueller39** [comment]
https://github.com/idehub/react-native-google-analytics-bridge/pull/185
