### ISSUE TITLE
What now that analytics force firebase analytics

### ISSUE THREAD

**Issue by ScreamZ** [idehub/react-native-google-analytics-bridge#182]
Hello,

just wanted to create a new property on my Google Analytics account, I checked Mobile App instead of Web Application. But they told me I had to use FireBase to make that kind of property.

What should I do ? Are you expecting to migrate to it ?

Best regards

**Comment by matteogabella** [comment]
hi, there is a workaround, given by google itself
check this
https://support.google.com/analytics/answer/2587086?hl=en&visit_id=1-636317179632979567-126840879&rd=1

**Comment by ScreamZ** [comment]
Thank you :)

**Comment by MadisonBlake** [comment]
This workaround doesn't look to hold true anymore. 

The only option for View is "All Web Site Data"
I see no option for "Create new view" or "Mobile app" from Google.


It appears Google is really forcing the transition to Firebase...

**Comment by ScreamZ** [comment]
@MadisonBlake You can use https://rnfirebase.io/, the documentation is well explained, I set it up and it's worked out pretty well. :)

Best regards

**Comment by cbrevik** [comment]
I am not sure where you're finding that @MadisonBlake.

But for me, under Admin -> View I find this;
![image](https://user-images.githubusercontent.com/4932625/33597951-57e751a6-d9a1-11e7-85b6-fc12d6be4153.png)
If I then select Create New View, I can select Mobile App;
![image](https://user-images.githubusercontent.com/4932625/33597979-6d493500-d9a1-11e7-9252-03dbd7d55542.png)

People can use Firebase if they want though, but I don't think Google is forcing anyone over yet.
