### ISSUE TITLE
Best practice for managing tracker

### ISSUE THREAD

**Issue by mobitinker** [idehub/react-native-google-analytics-bridge#184]
I'm still getting familiar with RN. Is there a recommended pattern for managing the tracker? Rather than creating it in each module used, should I do so once, store it in state and reuse? If so, where's the best place to create it? 

Thanks for writing this! Very useful!

**Comment by SaraChicaD** [comment]
Great Q, I'm having a similar question for develop/production accounts & GA IDs. To your point, I created a file (`GoogleAnalytics.js`) with different functions and exported them, importing each one into the necessary file -- that way you only have to write the logic once.

**Comment by cbrevik** [comment]
Hi, this has been asked (and answered) before, https://github.com/idehub/react-native-google-analytics-bridge/issues/104#issuecomment-274430960

Please search through issues before submitting new ones :)
