### ISSUE TITLE
Implement `requiresMainQueueSetup`

### ISSUE THREAD

**Issue by bfanger** [idehub/react-native-google-analytics-bridge#186]
react-native 0.49.3 generates a warning:
> Module RCTGoogleAnalyticsBridge requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by simonemarinelli** [comment]
+1

**Comment by RodrigoCS** [comment]
+1
