### ISSUE TITLE
android release build fail with DexException

### ISSUE THREAD

**Issue by rouge3351** [idehub/react-native-google-analytics-bridge#198]
i have a trouble at release build.
first, this is version that i use
react-native:0.49.3
react-native-google-analytics-bridge : 5.3.3

when i run react-native run-android, it works fine!

but when i command './gradlew assembleRelease' it throw DexException like this
`Error:Execution failed for task ':app:transformDexWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcl/json/BuildConfig;`

in my android app/gradle
`
android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "0.0.1"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    dexOptions {
        jumboMode true
    }
}
dependencies {
    compile project(':react-native-google-analytics-bridge')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.+"
    compile "com.facebook.react:react-native:+"  // From node_modules

   ..other library link
    compile 'com.google.android.gms:play-services-base:11.6.0'
    compile 'com.google.android.gms:play-services-maps:11.6.0'
}
`

anybody know about this problem ?
please help me!

**Comment by RobertSheaO** [comment]
@rouge3351 Try enabling multiDex in your `android/app/build.gradle` file inside the `defaultConfig` section.

Here's an example, of course, just add the `multiDeskEnabled true` line to your `defaultConfig` and don't wholesale replace with the following example.

###### android/app/build.gradle
```
android {
    defaultConfig {
        multiDexEnabled true
    }
}
```

**Comment by niom** [comment]
this should be closed

**Comment by pyqui** [comment]
Pretty simple, but it took me hours to figure it out. Many thanks.

**Comment by brenohq** [comment]
same error here..

**Comment by qdevelopergithub** [comment]
same here!! anyone please help?

**Comment by abdullateef97** [comment]
@qdevelopergithub check your build.gradle file and update all your dependencies to the latest version.
It's mostly a case of dependencies mismatch
