### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by 9mm** [idehub/react-native-google-analytics-bridge#2]
I keep getting the following error. I tried updating the packages via `android` but am not sure what else to look at.

    * What went wrong:
    A problem occurred configuring project ':GoogleAnalyticsBridge'.
    > Could not resolve all dependencies for configuration ':GoogleAnalyticsBridge:_debugCompile'.
       > Could not find com.google.android.gms:play-services-analytics:8.3.0.
         Searched in the following locations:
             file:/Users/Yoyo/.m2/repository/com/google/android/gms/play-services-analytics/8.3.0/play-services-analytics-8.3.0.pom
             file:/Users/Yoyo/.m2/repository/com/google/android/gms/play-services-analytics/8.3.0/play-services-analytics-8.3.0.jar
             https://jcenter.bintray.com/com/google/android/gms/play-services-analytics/8.3.0/play-services-analytics-8.3.0.pom
             https://jcenter.bintray.com/com/google/android/gms/play-services-analytics/8.3.0/play-services-analytics-8.3.0.jar
             file:/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-analytics/8.3.0/play-services-analytics-8.3.0.pom
             file:/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-analytics/8.3.0/play-services-analytics-8.3.0.jar
         Required by:
             Messenger:GoogleAnalyticsBridge:unspecified

**Comment by cbrevik** [comment]
Thanks for the feedback! Have you remembered to define the ANDROID_HOME env variable? See https://facebook.github.io/react-native/docs/android-setup.html#define-the-android-home-environment-variable

 I'll specify in the installation notes that you need the Google Play services SDK as well.

**Comment by 9mm** [comment]
Thanks a lot for your help.

I do have `ANDROID_HOME` specified, but I don't have Google Play services. I'm new to Android, where can I find the directions to install that?

Thanks!

**Comment by cbrevik** [comment]
[Here](https://developer.android.com/sdk/installing/adding-packages.html) is a more complete guide than I could write.

According to step 3 from that guide, you need three SDK packages; "Google Play services", "Google Repository" and the latest "Google APIs" to use Google Play from an emulator.
 
From the terminal, you should run just `android`, as a command, to open up the Android SDK Manager. For me the latest version installed is Android 6.0 API 23. Under that folder I check "Google APIs Intel x86 Atom_64 System Image", and the one below that which is not 64x.

Next you open up the Extras-folder, and check "Google Play services" and "Google Repository". Then you click "Install packages" down to the right.

Hope this is helpful!

**Comment by cbrevik** [comment]
[The React Native homepage](https://facebook.github.io/react-native/docs/android-setup.html#configure-your-sdk) also has more info on what it needs to run on Android, make sure you have all these SDK packages installed.

**Comment by 9mm** [comment]
Installing Google play services, Google repository, and Google API's fixed it!
