### ISSUE TITLE
Upgrade version of gms:play-services-analytics

### ISSUE THREAD

**Issue by sodik82** [idehub/react-native-google-analytics-bridge#20]
Currently I have conflicting version of google place services as I am using more 3rd party libs and I was not able to build android application.

Upgrade of services to latest version `com.google.android.gms:play-services-analytics:8.4.0` solved the issue. Thanks.

**Comment by cbrevik** [comment]
Presumably this would be a problem for others too. How do these third-party libraries mark their Google Play service dependency? 

Something like:
```gradle

dependencies {
    compile 'com.google.android.gms:play-services-analytics:8.+'
}
```
Or do they specify 8.4.0?

**Comment by 9mm** [comment]
I'm also wondering the same thing (just encountered a problem). How can I make sure it builds on the latest version?

**Comment by 9mm** [comment]
PS It's hilarious I stumbled across this issue 100% on accident, after spending hours trying to debug this and giving up.

Hooray for pleasant surprises 🎉

**Comment by sodik82** [comment]
The others updated it just to the newer version ( see https://github.com/lelandrichardson/react-native-maps/commit/dfbb51d6bf7c03713e450eeb998e89636651fd56 )

**Comment by cbrevik** [comment]
Alright, thanks! I will update this along with the other new feature in the next version of this module.

I will probably set it to `compile 'com.google.android.gms:play-services-analytics:8.+'` though, so I will not have to update the dependency for every minor version of play-services-analytics.
