### ISSUE TITLE
React Native 0.47 build issue

### ISSUE THREAD

**Issue by fitz0019** [idehub/react-native-google-analytics-bridge#202]
Hey,

I'm using React Native 0.49 and I'm having build issues on Android.

There is an error within GoogleAnalyticsBridgePackage.java

```
error: method does not override or implement a method from a supertype
    @Override
```

From researching it seems 0.47+ has deprecated the need to use @Override for createJSModules. For context here are a few other libraries that have since fixed the issue:

- https://github.com/airbnb/lottie-react-native/issues/166
- https://github.com/rebeccahughes/react-native-device-info/pull/191

The commit from React Native with the change: [facebook/react-native@ce6fb33](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8)

Sorry if this issue has already been reported, I've had a look and couldn't see one related.

Thanks,

Fitz

**Comment by RobertSheaO** [comment]
@fitz0019 This was fixed back on August 2. I currently use version 5.3.3 and it's not an issue

https://github.com/idehub/react-native-google-analytics-bridge/commit/9c2757807cae55a84f715159015fdc9cc7acc127#diff-b30d7dc8ba41e307aa3f8e48398b724b

Please make sure to use the latest release which at this time is 5.4.1

https://www.npmjs.com/package/react-native-google-analytics-bridge

**Comment by fitz0019** [comment]
@RobertSheaO I will have to checkout version 5.4.1. I was confused because on Master and even the latest tags on this repo I can see still the `@Override` within the code.

[GoogleAnalyticsBridgePackage.java](https://github.com/idehub/react-native-google-analytics-bridge/blob/1f4331524705805f22f4f897581ae78a542f0269/android/src/main/java/com/idehub/GoogleAnalyticsBridge/GoogleAnalyticsBridgePackage.java#L32)

**Comment by fitz0019** [comment]
@RobertSheaO Ah, sorry I will try 5.4.1. Thanks for your help.
