### ISSUE TITLE
error: method does not override or implement a method from a supertype @Override

### ISSUE THREAD

**Issue by laurabarrera11** [idehub/react-native-google-analytics-bridge#205]
Hi, 
I'm trying to use this package and I'm linking Android manually. I'm getting this error:
/Users/laurabarrera/hotplate/android/app/src/main/java/com/hotplate/MainApplication.java:61: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: /Users/laurabarrera/hotplate/android/app/src/main/java/com/hotplate/MainApplication.java uses or overrides a deprecated API.

I tried removing @Override from MainApplication.java but then the package doesn't link correctly and gives me the "Undefined is not an object.." error. I would appreciate any suggestion to fix this. Thanks!

**Comment by cbrevik** [comment]
This does not seem to be an error specific this library, rather in your own app code.
