### ISSUE TITLE
Error connecting to Tag Manager on Android

### ISSUE THREAD

**Issue by diegovillelga** [idehub/react-native-google-analytics-bridge#218]
### Environment

react-native 16.0.0
the problem only on Android
compileSdkVersion 23
buildToolsVersion "23.0.1"

### Steps to Reproduce

Into de index.android.js this code no return..
`GoogleTagManager.openContainerWithId('GTM-XXXXXX')
            .then(() => {
                return GoogleTagManager.stringForKey('pack');
            })
            .then(pack => {
                console.log('Pack: ', pack);
            })
            .catch(err => {
                console.log(err);
            });`

Into de Andoid code:
`PendingResult<ContainerHolder> pending = mTagManager.loadContainerPreferFresh(containerId, -1);
        pending.setResultCallback(new ResultCallback<ContainerHolder>() {
            @Override
            public void onResult(ContainerHolder containerHolder) {
                if (containerHolder != null && containerHolder.getStatus().isSuccess()) {
                    mContainerHolder = containerHolder;
                    promise.resolve(true);
                } else {
                    promise.reject(E_OPEN_CONTAINER_FAILED, new Throwable(String.format("Failed to open container. Does container with id %s exist?", containerId)));
                }
                openOperationInProgress = false;
            }
        }, 2000, TimeUnit.MILLISECONDS);`

containerHolder status is always:
Status{statusCode=TIMEOUT, resolution=null}

Same code into index.ios.js, works perfect

**Comment by cbrevik** [comment]
I'm sorry, I'm not quite sure I understand. You're getting a Promise-rejection and ContainerHolder-status inside [`onResult`](https://github.com/idehub/react-native-google-analytics-bridge/blob/436f63cb333ce74fd554b0b726b2a5fcb6e0135d/android/src/main/java/com/idehub/GoogleAnalyticsBridge/GoogleTagManagerBridge.java#L61) is `TIMEOUT`?

Can you supply `adb logcat` logs around when it happens?

**Comment by diegovillelga** [comment]
Yes, that's the problem
adb logcat:

`01-29 18:27:04.312 5623-5623/com.simplecounter E/GoogleTagManager: timer expired: setting result to failure
01-29 18:27:26.340 5623-5623/com.simplecounter I/Choreographer: Skipped 1321 frames!  The application may be doing too much work on its main thread.
01-29 18:27:26.341 5623-5709/com.simplecounter I/ReactNativeJS: { [Error: Failed to open container. Does container with id GTM-XXXXX exist?] framesToPop: 1, code: 'E_OPEN_CONTAINER_FAILED' }`

GTM-CODE it's OK,  iOS works fine

**Comment by cbrevik** [comment]
If you know how, it'd be cool if you could edit the Android code under [this line](https://github.com/idehub/react-native-google-analytics-bridge/blob/436f63cb333ce74fd554b0b726b2a5fcb6e0135d/android/src/main/java/com/idehub/GoogleAnalyticsBridge/GoogleTagManagerBridge.java#L54) and add `mTagManager.setVerboseLoggingEnabled(true);`

That is to say the file that is under `<project>/node_modules/react-native-google-analytics-bridge/android/src/main/java/com/idehub/GoogleAnalyticsBridge/GoogleTagManagerBridge.java`

And check `adb logcat` again when this error occurs.

**Comment by diegovillelga** [comment]
Now it's working without changing anything ...

Probably the GTM Code has taken a while to refresh in google systems ... the only thing that occurs to me ...
The GTM Code was discharged about 8 hours ago and has been failing until now

Thanks and sorry..

**Comment by uc-asa** [comment]
I'm getting same issue, could you help plz.
