### ISSUE TITLE
Allow advertising features

### ISSUE THREAD

**Issue by 9mm** [idehub/react-native-google-analytics-bridge#22]
Hey, I think it would be really helpful to have a config option that lets you enable advanced advertising features. Here's a description of how to enable for both iOS and Android (could default to false):

https://support.google.com/analytics/answer/2444872?hl=en&utm_id=ad&authuser=0#app

This will allow you to turn this switch on inside GA:

![image](https://cloud.githubusercontent.com/assets/1386207/13899892/5ef4f558-edcf-11e5-9ff5-cf311bf8cfde.png)

**Comment by cbrevik** [comment]
Hi @9mm! This is actually already a thing, you can enable advertisingId collection by calling [GoogleAnalytics.allowIDFA(true)](https://github.com/idehub/react-native-google-analytics-bridge#allowidfaenabled).

As it says, you will have to have done the optional step 7 from the [installation guide for iOS](https://github.com/idehub/react-native-google-analytics-bridge#manual-installation-ios):

> **Optional step**: If you plan on using the advertising identifier (IDFA), then you need to do two things:
  1. Add AdSupport.framework under "Link Binary With Libraries". (As with the other frameworks in step 5).
  2. Go to Xcode ➜ `Libraries` ➜ `RCTGoogleAnalyticsBridge.xcodeproj` ➜ right-click `google-analytics-lib`. Here you need to `Add files to ..`, and add `libAdIdAccess.a` from the `google-analytics-lib` directory. This directory is located in the same `node_modules` path as in step 3.

Only do this if you actually plan to use advertising features in your app, if not it might get rejected by the AppStore for including `libAdIdAccess.a` and not using ads. This is why I do not include this lib by default.

I might consider updating the README to more accuratly reflect what `allowIDFA` means. :+1:

**Comment by 9mm** [comment]
Oh... Very interesting. So 2 questions:

1. The advertising Id that you mentioned is the same thing that allows me to see advanced demographic info, etc (the toggle basically)?

2. Are any extra steps needed on android?

Thanks!

**Comment by cbrevik** [comment]
1) Not exactly. If you look into the link you pasted, the code changes you need (for the toggle to have any effect) is to "allowIDFA". For Android that is running `tracker.enableAdvertisingIdCollection(true)`, and for iOS that is `tracker.allowIDFACollection = YES`. This is what happens if you do `GoogleAnalytics.allowIDFA(true)` in JS. Actually enabling the toggle is up to you :)

2) No, nothing extra for Android. Just remember to run `GoogleAnalytics.allowIDFA(true)`.

**Comment by 9mm** [comment]
Ah, very interesting!

I have one more somewhat noob question. Where's the best place to put `GoogleAnalytics.allowIDFA(true)` so I only have to call it once? Right now I have `trackScreenView` set everywhere in my app. I assume I only need to call the IDFA function once though?

**Comment by cbrevik** [comment]
Yes, allowIDFA is a config function, and you only need to call it once. Typically I would put it in one of the entry-point files like `index.ios.js` and `index.android.js`. Or in some common component which is used in both iOS/Android, but not re-loaded again after app startup. 

You don't even need to put it inside a component class, but just do it right away at the top;
```javascript
const GoogleAnalytics = require('react-native-google-analytics-bridge');
GoogleAnalytics. allowIDFA(true);
```

**Comment by 9mm** [comment]
Thanks. That's all very helpful!

One final question if you don't mind. I followed the instructions for optional step 7 but I noticed when you drag the missing file Into the project via "add to..." In menu, it doesn't actually store anything in my projects Xcode file. 

I'm afraid that I'll clear node modules in future and forget, or someone on my team will forget. Is there a way I can check that change into version control?

Thanks again. This is a great library.

**Comment by cbrevik** [comment]
What you could do is adding the project file to your version control after doing the instructions in step 7. It is located under `node_modules/react-native-google-analytics-bridge/ios/RCTGoogleAnalyticsBridge/RCTGoogleAnalyticsBridge.xcodeproj/project.pbxproj`. Then you will see if it changes after cleans, or newer versions of this library.

I know this is probably not what you want to hear, it is a bit more hassle. I cannot add this file by default because most will not use it, and if it is included without ads being used, then the app has a much higher chance of being rejected.

**Comment by holyxiaoxin** [comment]
@9mm Did you get it to work? I'm trying to access the demographics tab in Google Analytics but it's still asking me to validate my tracking code.

Here's what I'm doing:

```js
// Called once when app starts
export const init = () => {
  GoogleAnalytics.setTrackerId(googleAnalyticsTrackingId);
  GoogleAnalytics.allowIDFA(true);
}
```

Just by running the app, I would be setting IDFA right? I've checked out the dashboard after 24hours but it's still asking me to validate my tracking code. Is there anything that I'm not understanding right?

**Comment by cbrevik** [comment]
I haven't tested this myself @holyxiaoxin, just a quick Google search gives me [this](http://stackoverflow.com/questions/36703659/cant-validate-tracking-code-for-demographic-reports-using-google-analytics-ios-s?answertab=active#tab-top).

Maybe just try to skip it? Else maybe @9mm has some better idea.

And yes, just by running the app and calling the `allowIDFA(true)` function it should be set. As long as you've included the necessary `libAdIdAccess.a` framework of course.

**Comment by stilllife00** [comment]
Is it correct to say that now the correct syntax is 

    let tracker1 = new GoogleAnalyticsTracker(googleAnalyticsTrackingId);
    tracker1.allowIDFA(true);

?
