### ISSUE TITLE
cannot read property trackScreenView of undefined

### ISSUE THREAD

**Issue by manjubasha** [idehub/react-native-google-analytics-bridge#224]
### Environment
react-native-cli: 2.0.1
react-native: 0.51.0
react-native-google-analytics-bridge: 5.6.0
platform: Only iOS and it works fine on Android

### Steps to Reproduce

```
import {
  GoogleAnalyticsTracker,
  GoogleAnalyticsSettings
} from 'react-native-google-analytics-bridge';

```
Imported the package and used it as mentioned below in `componentDidMount()` function

```
let tracker1 = new GoogleAnalyticsTracker("AA-00000000-1", { 'PDEVENT': 'HERE IS THE EVENT' });
    tracker1.trackScreenView("PDPage");
    tracker1.trackEvent("Customer", "New");
    GoogleAnalyticsSettings.setDispatchInterval(1);
```

I checked linking of the package with Android and iOS several times both automatically through react-native link and manually adding them

I connected remote debugger, added node_modules to the workspace in sources tab and kept breakpoint in GoogleAnalyticsTracker.js -> trackScreenView
Though I see the function getting executed, i am still receiving the error.

### Expected Behavior
I expected the event to show up and screen to be captured in GA Console

### Actual Behavior
Instead i received an error saying `cannot read property trackScreenView of undefined` when i navigated to the screen.

I am not sure what i am missing.

**Comment by cbrevik** [comment]
If the debugger breaks into `trackScreenView` in `GoogleAnalyticsTracker` then the native module (`GoogleAnalyticsBridge`) is not getting loaded. 

This is most likely because of faulty installation or linking. I would recommend trying again, or supplying a simple demo project on Github where this is reproduced.

**Comment by manjubasha** [comment]
Hi cbrevik,

I think there was some caching issue. I deleted the repo pulled it again and its working.
I am able to see the events.
