### ISSUE TITLE
Demographics and Interest Reports aren't received in GA, any idea ?

### ISSUE THREAD

**Issue by MaheshNandam** [idehub/react-native-google-analytics-bridge#226]
Issue:

Demographics and interest reports weren't received in google analytics dashboard, remaining data like real-time devices, audience (Active users, App versions, etc) data is receiving by the GA, 

@cbrevik, Can you please help me to understand why GA is not receiving the data?

### Environment

		"react": "16.0.0",
		"react-native": "0.50.4",
		"react-native-google-analytics-bridge": "^5.3.3",

### Code:
const tracker = new GoogleAnalyticsTracker('UA-90616671-1');

//Enable IDFA
tracker.allowIDFA(true);

//time interval to send the batches to GA
GoogleAnalyticsSettings.setDispatchInterval(30);

// disabled the googleAnalytics while test or debug
GoogleAnalyticsSettings.setDryRun(false);

Thanks.

**Comment by MaheshNandam** [comment]
@MrBr @gnestor @nikolaia, can you please anyone help me on this?

Thanks a lot.

**Comment by cbrevik** [comment]
Is this a IDFA feature?: https://github.com/idehub/react-native-google-analytics-bridge#allowidfaenabled

**Comment by MaheshNandam** [comment]
As per GA doc [https://support.google.com/analytics/answer/2444872?hl=en&utm_id=ad](url) to get demographics and interests we need to enable the IDFA right!.

**Comment by cbrevik** [comment]
Yep, do that! Closing issue then

**Comment by MaheshNandam** [comment]
Nonetheless, I haven't received the data under demographics and interests data?

**Comment by cbrevik** [comment]
We do nothing special with IDFA, so I don’t think the fault is in this library

**Comment by MaheshNandam** [comment]
Okay make sense, 

But I couldnt find the reason to solve this issue, does this library supports to get the data in GA for demographics and interest?

**Comment by MaheshNandam** [comment]
Demographics and interest data started reflecting in GA after 1 week of live app release.

@cbrevik, As you said no problem from library side and Thanks for your time.

**Comment by cbrevik** [comment]
Awesome @MaheshNandam, glad it worked out
