### ISSUE TITLE
react native more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by SkyFred27** [idehub/react-native-google-analytics-bridge#231]
Issue:
react native more than one library with package name 'com.google.android.gms.license'

Solution
https://github.com/facebook/react-native/issues/18479

don't use 
compile 'com.google.android.gms:play-services-analytics:+'

instead of + a real version number

**Comment by cbrevik** [comment]
Hi see https://github.com/idehub/react-native-google-analytics-bridge#use-environments-google-service-version-due-to-crash-on-google-service-version-12
