### ISSUE TITLE
[Type System] Suggestion to make OptionalValue interface's attributes really optional

### ISSUE THREAD

**Issue by pedpess** [idehub/react-native-google-analytics-bridge#236]
Hi,

In the `v5.5.0` was introduced some updates in the type system. The **OptionalValue**  interface has its attributes (label and value) set as mandatory and not optional. Here's the diff: https://github.com/idehub/react-native-google-analytics-bridge/commit/f2c09f0c5ebba6d106847996896ca4f448f96f36#diff-b52768974e6bc0faccb7d4b75b162c99R22

Is there any reason for that? GA Documentation says that label and value from the `trackEvent` implementation should the optional by default.

**Anatomy of Events**
An Event has the following components. An Event hit includes a value for each component, and these values are displayed in your reports.

 - Category
 - Action
 - Label (optional, but recommended)
 - Value (optional)

Source: https://support.google.com/analytics/answer/1033068?hl=en

Thanks in advance and good work with the lib =)

**Comment by cbrevik** [comment]
Hi, I think you're correct @pedpess.

I'm actually working on a TypeScript-based branch of the lib, in which they are both optional: https://github.com/idehub/react-native-google-analytics-bridge/blob/bfa03f09081cdb9816872700a9e94d20108e28fa/src/GoogleAnalyticsTracker.ts#L101
Still going to take some time to get that done though.

I've published a `5.6.3` which fixes this in master through. Please verify that it fixes in, and close issue in that case.

**Comment by pedpess** [comment]
Hey, @cbrevik thanks for the response and the work done in this new branch =). I bumped into the version you mentioned and now it's working as expected.

I'm closing this issue.
