### ISSUE TITLE
[react-native version > 0.50]react-native link react-native-google-analytics-bridge failed in iOS when you have your own Podfile in ios project

### ISSUE THREAD

**Issue by malonguwa** [idehub/react-native-google-analytics-bridge#241]
### Environment

(Which react-native version? What version of this library? iOS, Android, or both?)
react-native: 0.50.3
react-native-google-analytics-bridge: 5.6.3
I installed GoogleMobileAdSDK via cocapods

### Actual Behavior
1. npm install --save react-native-google-analytics-bridge
2. react-native link react-native-google-analytics-bridge
3. Then link fail in iOS, 
rnpm-install info Android module react-native-google-analytics-bridge is already linked 
rnpm-install info Linking react-native-google-analytics-bridge ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined 
Please file an issue here: https://github.com/facebook/react-native/issues

**Comment by malonguwa** [comment]
And after I do a clean install for my current project **without** adding react-native-google-analytics-bridge and also **without** run pod install to install the GoogleMobileAdSDK I was using. And then I install react-native-google-analytics-bridge, and react-native link, it is not show any error, but then I run pod install in ios folder, I got the following result, and my podfile has a new pod command "pod 'react-native-google-analytics-bridge', :path => '../node_modules/react-native-google-analytics-bridge'". Then when I run the Xcode, I got React/RCTBridgeModule.h' file not found Error in RCTGoogleTagManagerBridge.h

I do not think pod install will need to install React or react-native-google-analytics-bridge. Am I doing wrong? How to get this linked......

 pod install
Analyzing dependencies
Fetching podspec for `react-native-google-analytics-bridge` from `../node_modules/react-native-google-analytics-bridge`
Downloading dependencies
Installing Google-Mobile-Ads-SDK (7.30.0)
Installing React (0.11.0)
Installing react-native-google-analytics-bridge (5.6.3)
Generating Pods project
Integrating client project

**Comment by malonguwa** [comment]
I think react-native-google-analytics-bridge.podspec file caused this link fail issue. According to the info i found from https://github.com/Microsoft/react-native-code-push/issues/1085

"If your iOS project is using CocoaPods (contains Podfile) and linked library has podspec file, then react-native link will link library using Podfile. To support non-trivial Podfiles add # Add new pods below this line comment to places where you expect pods to be added"

But in my case I just have a simple Podfile, I am not sure what should I do to make auto link work....

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target “myProject” do
pod 'Google-Mobile-Ads-SDK'
end

```

**Comment by eAAwan** [comment]
Instead of linking it automatically I use manually linking and if fix all the issues.
https://github.com/idehub/react-native-google-analytics-bridge/wiki/Manual-installation
