### ISSUE TITLE
Setting User Properties

### ISSUE THREAD

**Issue by georific** [idehub/react-native-google-analytics-bridge#242]
I was wondering is this supported, I wasn't able to find any docs on this component that supports it.

https://developers.google.com/analytics/devguides/collection/firebase/android/properties

**Comment by cbrevik** [comment]
Hi @georific. That functionality is Firebase-specific, so not quite like that.

We do however support `setUser`, as well as tracking [custom dimensions/metrics](https://developers.google.com/analytics/devguides/collection/android/v4/customdimsmets) along with screen views and events.
