### ISSUE TITLE
android support libraries mixing versions

### ISSUE THREAD

**Issue by BatDroid** [idehub/react-native-google-analytics-bridge#243]
### Environment

(android)

### Steps to Reproduce

`./gradlew build`

### Expected Behavior

build project

### Actual Behavior

error:
`/node_modules/react-native-google-analytics-bridge/android/build.gradle: Error: All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 26.1.0, 23.0.1. Examples include com.android.support:support-compat:26.1.0 and com.android.support:appcompat-v7:23.0.1 [GradleCompatible]`

**Comment by hpelitebook745G2** [comment]
any updates on this?
