### ISSUE TITLE
RCTGoogleTagManagerBridge.h: 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by sanjayholla94** [idehub/react-native-google-analytics-bridge#249]
### Environment
react-native: 0.47.1
react-native-google-analytics-bridge: 5.6.3
Platform: iOS

### Steps to Reproduce
Followed the manual installation procedure as react native link did not work due to a different folder structure. Completed all the steps excluding the optional step but it failed to compile with the following error on ios.
`/Users/root/react-native-workspace/test_analytics/node_modules/react-native-google-analytics-bridge/ios/RCTGoogleAnalyticsBridge/RCTGoogleAnalyticsBridge/RCTGoogleTagManagerBridge.h:1:9: 'React/RCTBridgeModule.h' file not found
`
Note: The manual installation on Android works fine.

### What I tried

The solutions provided for other similar issues in this project and stackoverflow did not work. 

Also modified Build Settings -> Header Search Path to point to an absolute path of `react-native/React`.  However it was still unable to find RCTBridgeModule.h

I've tried every possible solution I could think of and nothing has worked. Please help me in solving this issue.

Note: React native was installed via Cocoapods

**Comment by f03seitz** [comment]
+1

**Comment by jan-happy** [comment]
+1

**Comment by wesleyvandevoorde** [comment]
No solution for this problem?
