### ISSUE TITLE
Error:Execution failed for task ':react-native-google-analytics-bridge:processDebugResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by sanilcgs** [idehub/react-native-google-analytics-bridge#263]
I have installed react-native-google-analytics-bridge package into my project. Then I tried to build the project and got the below error.
```
/Users/sanil/workspace/kazhutha/client/node_modules/react-native-google-analytics-bridge/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
/Users/sanil/workspace/kazhutha/client/node_modules/react-native-google-analytics-bridge/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml
Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
Error:Execution failed for task ':react-native-google-analytics-bridge:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```
My current configuration is

```buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
```

But the issue occurred in android only, iOS its works fine. So is there any configuration issue with my gradle file? If so, what all changes should I do??

**Comment by bashirpour** [comment]
Yeah I have the same problem

**Comment by FransTwisk** [comment]
Same here when trying to upgrade from react-native 0.55.3 to 0.56, so something changed there breaking it.

**Comment by drewandre** [comment]
I'm seeing this same error with RN 0.56. iOS builds fine but android gives that same error -- "Error retrieving parent for item: No resource found that matches the given name".
`"react": "16.4.1",
"react-native": "0.56.0",
"react-native-google-analytics-bridge": "^5.8.0",`

`android {
    compileSdkVersion 26
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
        ....
     }
     ...
}`

**Comment by FransTwisk** [comment]
Any update on this? Any temporary workaround? Really want to move forward and upgrade React-Native but can't because of this.

**Comment by FransTwisk** [comment]
Found a workaround here, by forcing all subprojects to use a specific SDK version: https://github.com/wix/react-native-navigation/issues/2209#issuecomment-405843895

**Comment by cbrevik** [comment]
That is a fine workaround, version `6.1.0` of this library also allows you to override easily in `ext`:
https://github.com/idehub/react-native-google-analytics-bridge/blob/fc2d72a81d72ca435894d8150ba5695122bfb2eb/examples/postRN56Example/android/build.gradle#L37
