### ISSUE TITLE
issue with products data when using trackMultiProductsPurchaseEvent

### ISSUE THREAD

**Issue by himelbrand** [idehub/react-native-google-analytics-bridge#265]
### Environment

iOS, Android 
RN 0.51.0

### Steps to Reproduce

I tried using the purchase multiple products method 
### Expected Behavior

to see the products and the transaction in the google analytics dashboard

### Actual Behavior

in the google analytics dashboard:
under Ecommerce -> sales preformance I see my transactions, with the orderid and the revenue, but inside the transaction there are no products

also in the product preformance tab there are no products...

what to do?

### Code sample/demo project
```javascript
let track_products = products.map((product)=>{
            return({
                id:String(product.product_id),
                name:product.product_title,
                category:product.categories[0].category_title,
                brand:product.warehouse.warehouse_name,
                quantity:product.cart_pack_qua,
                variant:String(product.pack_option.shp_pack_id),
                price:parseFloat(product.srp)
            })
        })
        let transaction = {
            id:String(orderId),
            revenue:parseFloat(total),
        }
        trackMultiProductsPurchaseEvent(track_products,transaction,'Ecommerce','Purchase')

```

**Comment by cbrevik** [comment]
Hi! `trackMultiProductsPurchaseEvent` no longer exists, and the ecommerce has been rewritten in 6.0+. Could you test again with a newer version of the lib?
