### ISSUE TITLE
`pushDataLayerEvent` not sending any data to GTM

### ISSUE THREAD

**Issue by nathanziarek** [idehub/react-native-google-analytics-bridge#266]
### Environment

React 16.3.1
React Native 0.55.3
iOS Simulator

### Steps to Reproduce

1. Create a new Tag in Google Tag Manager (UA Event).
2. Create a trigger in GTM that looks for a custom event named "DEBUG" and fires the tag in #1.
3. Run the code at the bottom of the issue.

### Expected Behavior

Within Google Analytics, an event should show up in the real time reports.

### Actual Behavior

No event in real time reports.

Several things were done to test this:

1. On a website running the exact same instance of GTM, the console was opened and a dataLayer event pushed:

   ```
   dataLayer.push({"event": "DEBUG", "message": "test from website"});
   ```

   The event showed up nearly instantly in the Google Analytics interface.

2. Using the GoogleAnalyticsTracker code right next to the GTM code also pushed a successful event (see it in the code sample below). This "proves" that the simulator has access to the internet.

### Code sample/demo project

```
import {
    GoogleAnalyticsTracker,
    GoogleTagManager
} from "react-native-google-analytics-bridge";

const tracker = new GoogleAnalyticsTracker("UA-XXXXX-X");

GoogleTagManager.openContainerWithId("GTM-XXXXXXX")
    .then(() => {
        GoogleTagManager.setVerboseLoggingEnabled(true);
    })
    .then(() => {
        return GoogleTagManager.pushDataLayerEvent({
            event: "DEBUG",
            message: "test from pushDataLayerEvent()"
        });
    })
    .then(success => console.log(success))
    .catch(err => {
        console.log(err);
    });

tracker.trackEvent("DEBUG", "test from tracker()");
```

**Comment by cbrevik** [comment]
Hi! Could you provide logs from the XCode output window when doing this?

Also, I don't have the same setup with a website, so wondering if maybe the container type matters. I.e. when you create the container:
![image](https://user-images.githubusercontent.com/4932625/45802762-05ac9180-bcb8-11e8-8888-fb9f159b9c88.png)

One thing to test would be creating an "iOS" container and check if that matters. It does matter on the Google Analytics side which type of GA "property" you create: https://github.com/idehub/react-native-google-analytics-bridge/wiki/Creating-a-Google-Analytics-property-for-mobile-analytics

**Comment by clundberg1** [comment]
@cbrevik
I'm having the same problem. If I use the GoogleAnalyticsTracker, I can push events and see them in GA, but if I try using the GoogleTagManager to push enhanced ecommerce events, then it doesn't seem to work. It's also my first time trying to implement GTM, so I'm not really sure if I've configured the container or the tags incorrectly.

As you can see in my code, I'm simply trying to push an event taken from the GTM enhanced ecommerce docs:

```
GoogleTagManager.openContainerWithId("GTM-T9VS75T")
  .then(() => {
    return GoogleTagManager.pushDataLayerEvent({
      'event': 'productClick',
      'ecommerce': {
        'currencyCode': 'EUR',                       // Local currency is optional.
        'impressions': [
         {
           'name': 'Triblend Android T-Shirt',       // Name or ID is required.
           'id': '12345',
           'price': '15.25',
           'brand': 'Google',
           'category': 'Apparel',
           'variant': 'Gray',
           'list': 'Search Results',
           'position': 1
         },
         {
           'name': 'Donut Friday Scented T-Shirt',
           'id': '67890',
           'price': '33.75',
           'brand': 'Google',
           'category': 'Apparel',
           'variant': 'Black',
           'list': 'Search Results',
           'position': 2
         }]
      }
    })
  })
  .then(success => {
    console.log(success);
  })
  .catch(err => {
    console.log(err);
  });
```

As for the tag configuration, here's a screenshot in case something's wrong on my end:
![image](https://user-images.githubusercontent.com/29963339/47117191-51a41500-d229-11e8-8f85-93f1e8acc40e.png)

The container is Android (Legacy). Tag type is GA - Universal Analytics, and enhanced ecommerce features are enabled alongside the data layer, and it should be triggered by any event. So assuming everything is correct, I'm not sure why calls to pushDataLayerEvent() don't seem to appear in my GA.

**Comment by codesinghanoop** [comment]
@clundberg1 The same thing is happening with me. Did you find any work around?

**Comment by cbrevik** [comment]
It would be cool if you could do a `GoogleTagManager.setVerboseLoggingEnabled(true)` and check `adb logcat` in terminal (if this is Android we're talking about).

This will narrow down if the problem is with the library, or a problem with GTM <-> GA. If the logs says that the event was sent, then I'm leaning towards the latter.

**Comment by codesinghanoop** [comment]
@cbrevik 
 I tried to investigate in the library, what i found is if pushDataLayerEvent is triggered then in native side it checks if everything is good it sends a promise back through the bridge. See the below code snippet for reference.

```
if (mContainerHolder != null && isValidMapToPushEvent(dictionary)) {
          getDataLayer().push(ConvertReadableToMap.getMap(dictionary));
          promise.resolve(true);
}
```

**Comment by codesinghanoop** [comment]
Please see below logs, it seems suspicious.

```
10-04 11:41:29.682 12431 17372 W GoogleTagManager: Failed to load the container. No default container resource found with the resource ID -1
10-04 11:41:29.683 12431 17372 V GoogleTagManager: loadAfterDelay: containerId=GTM-XXXXXXX delay=0
10-04 11:41:29.684 12431 17372 D GoogleTagManager: Setting CTFE URL path: /r?id=GTM-XXXXXXX&gtm_auth=XXXXXXX&gtm_preview=5
10-04 11:41:29.684 12431 17372 D GoogleTagManager: Setting previous container version: 
10-04 11:41:29.687 12431 17389 V GoogleTagManager: Start loading resource from network ...
 
```

**Comment by clundberg1** [comment]
> It would be cool if you could do a `GoogleTagManager.setVerboseLoggingEnabled(true)` and check `adb logcat` in terminal (if this is Android we're talking about).
> 
> This will narrow down if the problem is with the library, or a problem with GTM <-> GA. If the logs says that the event was sent, then I'm leaning towards the latter.

Is something wrong?
> 10-18 17:10:53.933 12969 13025 I GoogleTagManager: Obtained fresh AdvertisingId info from GmsCore.
> 10-18 17:10:53.937 12969 13011 E GoogleTagManager: Invalid macro: _gtm.loadEventEnabled
> 10-18 17:10:53.939 12969 13028 V GoogleTagManager: Attempting to load resource from disk
> 10-18 17:10:53.939 12969 13028 D GoogleTagManager: Failed to find the resource in the disk
> 10-18 17:10:53.940 12969 13028 V GoogleTagManager: loadAfterDelay: containerId=GTM-T9VS75T delay=0
> 10-18 17:10:53.940 12969 13028 D GoogleTagManager: Setting previous container version:
> 10-18 17:10:53.942 12969 13029 V GoogleTagManager: Start loading resource from network ...

**Comment by clundberg1** [comment]
@codesinghanoop
I tried uninstalling the app from the emulator and running again and it didn't work.

**Comment by codesinghanoop** [comment]
@clundberg1 After reading the issue description i think you are using the same container for web and mobile. Please add .then in dataLayer.push({"event": "DEBUG", "message": "test from website"}); to check that promise is resolved and also add .catch to see if there is a error.

**Comment by clundberg1** [comment]
@codesinghanoop 
If you look at the code I posted, there's then() and catch(). The promise resolves successfully and prints true (no error).

**Comment by IlifilzaRusli** [comment]
I also have the same issue, I've pushed several events but I don't see them on GA. My container for iOS/Android is Legacy. The promise return 'success' however. 

 ```
GoogleTagManager.openContainerWithId(gtmContainerId)
   .then(() => 
        GoogleTagManager.pushDataLayerEvent({
          event: "open_app",
        })
          .then(success => console.log(success))
          .catch(err => {
            console.log('GTM err', err);
          })
      );
```


@clundberg1 do you find any solutions to this issue? 
@codesinghanoop if the event is pushed successfully, then you can see the events on GA right away?
