### ISSUE TITLE
Native module cannot be null.

### ISSUE THREAD

**Issue by masiamj** [idehub/react-native-google-analytics-bridge#267]
### Environment

React Native Version: **0.50.0*
React Native Google Analytics Bridge: **^5.8.0**
Platform: iOS

### Steps to Reproduce

```bash
yarn add react-native-google-analytics-bridge
react-native link react-native-google-analytics-bridge
```

I try to use the library as suggested in the docs.

### Expected Behavior

The app would boot with the ability to send events and screen hits to Google Analytics.

### Actual Behavior

The app fails to load with the following error:

<img width="422" alt="screen shot 2018-07-25 at 2 39 16 pm" src="https://user-images.githubusercontent.com/7084914/43220678-9dd1f922-9018-11e8-8a6c-4243a4250b8b.png">

### Code sample/demo project

This occurs once I insert the line:

`import { GoogleAnalyticsTracker } from 'react-native-google-analytics-bridge'`

Thanks for your help!

**Comment by masiamj** [comment]
Update- this issue is resolved when downgrading to version `5.7.1`. Not sure what the diff is there but just a note!

**Comment by ericdcobb** [comment]
@masiamj I ran into a similar problem and realized I just needed to rebuild after I first linked the library. Maybe you rebuilt at some point while downgrading?

**Comment by spencewine** [comment]
I'm getting this error as well with 5.8.0.
<img width="479" alt="screen shot 2018-08-16 at 1 54 02 pm" src="https://user-images.githubusercontent.com/1612742/44228815-da380380-a15b-11e8-8c64-949262c6b914.png">

**Comment by ahmetabdi** [comment]
Get the same

**Comment by ahmetabdi** [comment]
@cbrevik Any ideas? this is on latest version on a new project

**Comment by cbrevik** [comment]
No I am not able to reproduce that, there has to be something else here. If I do the following, the test app works fine for me:

```bash
react-native init nativeModuleNull
cd nativeModuleNull/
yarn add react-native-google-analytics-bridge
react-native link react-native-google-analytics-bridge\n
echo "import { GoogleAnalyticsTracker } from 'react-native-google-analytics-bridge'" >> App.js
react-native run-ios
```
