### ISSUE TITLE
Could not find support-v4.aar (com.android.support:support-v4:25.2.0)

### ISSUE THREAD

**Issue by harikanammi** [idehub/react-native-google-analytics-bridge#273]
I am running sample application. I am using this module. In iOS it's working fine But in Android i am getting build error like this...
![screen shot 2018-08-27 at 3 45 08 pm](https://user-images.githubusercontent.com/31063894/44654709-39c1c900-aa10-11e8-9c4c-34a691688daf.png)

`My module version is :"react-native-google-analytics-bridge": "^5.4.0"`

Please give any suggestion

**Comment by cbrevik** [comment]
Is this still an error with version `6.1.0` of this library?
