### ISSUE TITLE
Program type already present: com.google.android.gms.internal.measurement.zzs

### ISSUE THREAD

**Issue by ivandiazmolina** [idehub/react-native-google-analytics-bridge#283]
### Environment

(Which react-native version? What version of this library? iOS, Android, or both?)

React native 0:56
compileSdkVersion 26
buildToolsVersion '27.0.3'
classpath 'com.android.tools.build:gradle:3.1.2'
classpath 'com.google.gms:google-services:3.2.1'
### Steps to Reproduce

When I put this library mix with react-native-firebase, I get this error and I cant compile, I have tried different things but finally I can not get rid of this error

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

I cant compile, I get this message

Program type already present: com.google.android.gms.internal.measurement.zzs
Message{kind=ERROR, text=Program type already present: com.google.android.gms.internal.measurement.zzs, sources=[Unknown source file], tool name=Optional.of(D8)}

When I remove react-native-google-analytics-bridge, error disappears and I can compile normally

This is my build.gradle

implementation project(':react-native-google-analytics-bridge')
    implementation(project(':react-native-firebase')) {
        transitive = false
    }
    implementation project(':react-native-svg')
    implementation project(':react-native-device-info')
    implementation project(':react-native-fetch-blob')
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:23.0.1'
    implementation 'com.facebook.react:react-native:+'

    // This should be here already
    //implementation project(':react-native-firebase')
    implementation project(':react-native-admob')

    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation "com.google.firebase:firebase-messaging:15.0.2"
    implementation "com.google.firebase:firebase-config:15.0.2"
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'

Thx in advance

**Comment by cbrevik** [comment]
Hi @ivandiazmolina 

My guess both `react-native-admob`, `react-native-firebase` and `react-native-google-analytics-bridge` is the problem here.

This is similar to #280 & #281, where conflicting play-services versions create errors like these

please check out this wiki post: https://github.com/idehub/react-native-google-analytics-bridge/wiki/Android-build-problems

**Comment by sfratini** [comment]
@ivandiazmolina  Were you able to solve it? I cant find which dependency I have to modify to make it build
