### ISSUE TITLE
Error build Rn 57.1 and react native one signal

### ISSUE THREAD

**Issue by ajiehatajie** [idehub/react-native-google-analytics-bridge#285]
im install react 57.1 and react native one signal and google analystics is error build`
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: com.google.android.gms.internal.measurement.zzdy

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/2.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/3.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/4.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/5.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/6.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/7.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/8.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/9.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/10.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/11.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/12.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/13.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/14.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/15.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/16.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/17.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/18.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/19.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/20.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/21.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/22.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/23.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/24.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/25.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/26.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/27.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/28.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/29.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/30.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/37.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/40.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/43.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/52.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/55.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/58.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/62.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/63.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/64.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/65.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/66.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/67.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/68.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/69.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/70.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/71.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/72.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/73.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/74.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/75.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/76.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/77.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/78.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/79.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/84.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/85.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/86.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/87.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/90.jar, /home/ajie/Documents/Project/RN/project/newproject/Ktpelmu/android/app/build/intermediates/transforms/dexBuilder/debug/91.jar
`

**Comment by cbrevik** [comment]
Hi, before opening an issue, read the docs and search existing issues.

See #283 
& https://github.com/idehub/react-native-google-analytics-bridge/wiki/Android-build-problems
