### ISSUE TITLE
JSON value '0' of type NSNumber cannot be converted to NSString

### ISSUE THREAD

**Issue by nbolender** [idehub/react-native-google-analytics-bridge#290]
### Environment

react-native@0.57.1
react-native-google-analytics-bridge@6.1.1
iOS@11.4

### Steps to Reproduce

Call trackEvent with eventMetadata, but without specifying a value. For example:

```
GoogleAnalytics.trackEvent("Events", "Switch Tab", {
	label: "Just Announced"
});
```

### Expected Behavior

Event is tracked without a `value` (since value is optional).

### Actual Behavior

Redbox with error "JSON value '0' of type NSNumber cannot be converted to NSString"

**Comment by cbrevik** [comment]
Released as `6.1.2` 👍
