### ISSUE TITLE
Ignored dist files?

### ISSUE THREAD

**Issue by farzadshafiee** [idehub/react-native-google-analytics-bridge#299]
Since the project has been migrated to TypeScript, the JS files have been ignored from the repository. I presume this is mainly to prevent bad PRs where people would manipulate the JS files instead of TypeScript sources. However, this breaks the ability to install the package from the Github repo.

This is important because, for example, a contributor forks the repo, fixes an issue, and then sends a PR, but until the PR has been merged into the main repo and the package is published, they need to use their own fork in during their automated build and tests.

Obviously, the PR cannot include the ignored files. As result, every fork needs to maintain a branch that includes the dist directory, and use that branch. It adds an additional maintenance overhead for the contributors.

I just wanted to know if there's a streamlined workflow for this issue. Right now, all I can think of is to have a `dist` branch which is automatically updated per each commit on master but has a different `.gitignore` file, but I am not sure if it's the right approach. I was also wondering if benefits of ignoring `dist` directory outweigh the problems it has created. It'd be great if some light could be shed on this decision.

**Comment by cbrevik** [comment]
Hi @farzadshafiee 

You've correctly identified why I don't want to include the `dist` folder in the git repository. 

Funny you should ask this question though, I just held a talk at ReactJS Oslo Meetup that touches on some of these points. And I have previously written a blog post on the approach I think is superior here:
https://blog.novanet.no/easier-react-native-upgrade-with-patch-package/

In short, I would recommend using the [`patch-package`](https://github.com/ds300/patch-package) tool (follow the setup from the repository, my blog post is a bit dated now). 

So with that setup, you could:
1. Run `yarn run build` in your updated `react-native-google-analytics-bridge` project-folder. 
2. Copy the `dist` folder to `<your-app>/node_modules/react-native-google-analytics-bridge/`.
3. Run `yarn run patch-package react-native-google-analytics-bridge` inside your app project folder

And then changes will be patched in automatically when your dependencies are installed.

**Comment by farzadshafiee** [comment]
Thanks for the clarification, @cbrevik. It makes sense now. 👍🏻
