### ISSUE TITLE
undefined is not a constructor (evaluating 'new _ReactNativeGoogleAnalyticsBridgeAnalyticsTracker("UA-12345-1")')

### ISSUE THREAD

**Issue by renishdeveloper** [idehub/react-native-google-analytics-bridge#303]
**This is the package.json file.**
{
  "name": "react-native-google-analytics-bridge",
   "version": "6.1.2",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-native-google-analytics-bridge": "^6.1.2"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  }
}

When i'm creating GoogleAnalyticsTracker constructor using **new** keywork with below code
 **let tracker = new GoogleAnalyticsTracker("UA-12345-1");**

I will get the error undefined is not a constructor (evaluating 'new _ReactNativeGoogleAnalyticsBridgeAnalyticsTracker("UA-12345-1")')

Thanks in advance...!

**Comment by cbrevik** [comment]
Hi, Expo is not supported, as noted in [README](https://github.com/idehub/react-native-google-analytics-bridge#installation-and-linking-libraries)
