### ISSUE TITLE
duplicate symbol TAGActualAdIdAccess.o

### ISSUE THREAD

**Issue by nasmuris** [idehub/react-native-google-analytics-bridge#315]
Hello, as we're using IDFA in out project, I've followed module installation together with option step 6. I'm not able to build the project now though as the build process fails  with error (see actual behaviour). Is the manual installation obsolete and there is no need to add `libAdIDAccess.a` anymore?
### Environment
```
"react-native": "0.55.3",
"react-native-google-analytics-bridge": "^7.0.0",
"react-native-google-analytics-bridge": "^5.2.2",
```
### Steps to Reproduce

Follow manual installation 

### Expected Behavior

no build error

### Actual Behavior
```duplicate symbol _OBJC_CLASS_$_TAGActualAdIdAccess in:
.../ios/Pods/GoogleIDFASupport/Libraries/libAdIdAccessLibrary.a(TAGActualAdIdAccess.o)
.../Build/Products/Debug-iphoneos/libRCTGoogleAnalyticsBridge.a(TAGActualAdIdAccess.o)
duplicate symbol _OBJC_METACLASS_$_TAGActualAdIdAccess in:
.../ios/Pods/GoogleIDFASupport/Libraries/libAdIdAccessLibrary.a(TAGActualAdIdAccess.o)
.../Build/Products/Debug-iphoneos/libRCTGoogleAnalyticsBridge.a(TAGActualAdIdAccess.o)
ld: 2 duplicate symbols for architecture arm64```

**Comment by cbrevik** [comment]
Hi @nasmuris. 

What is the "environment" you link there, is it two different versions of this library installed at the same time. Not even sure how that is possible?
