### ISSUE TITLE
Build Error on React Native 0.59.0 version

### ISSUE THREAD

**Issue by MrDatastorage** [idehub/react-native-google-analytics-bridge#319]
**Is this a bug report?**

YES - The is a Bug

**Environment**

react-native: 0.59.0
react: 16.8.3
react-native-maps: 0.23.0
Target: Android 28

**Build specs:**
buildToolsVersion = "28.0.3"
minSdkVersion = 16
compileSdkVersion = 28
targetSdkVersion = 27
supportLibVersion = "28.0.0"
googlePlayServicesVersion = "15.0.1"
androidMapsUtilsVersion = "0.5+" // Map Utils Needed

**Dependencies:**
com.android.tools.build:gradle:3.3.1
com.google.gms:google-services:3.2.1

**Steps to Reproduce**

Create Sample Project using React Native 0.59.0
Install ```react-native-google-analytics-bridge```
Run react-native run-android

**Expected Behavior**

Build Successfully

**Actual Behavior**

Build Failed

**Error Message**

```> Task :react-native-google-analytics-bridge:compileDebugRenderscript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':react-native-google-analytics-bridge:debugCompileClasspath'.
> Could not find com.google.android.gms:play-services-analytics:15.0.1.
  Required by:
      project :react-native-google-analytics-bridge
> Could not find com.google.android.gms:play-services-tagmanager-v4-impl:15.0.1.
  Required by:
      project :react-native-google-analytics-bridge```

**Comment by cbrevik** [comment]
Hi, I recommend reading the wiki post I wrote on the topic of conflicting Play Services versions between libraries: 
https://github.com/idehub/react-native-google-analytics-bridge/wiki/Android-build-problems

You've set `googlePlayServicesVersion = "15.0.1"`, but there is no v15.0.1 of those SDKs: 
* https://mvnrepository.com/artifact/com.google.android.gms/play-services-analytics
* https://mvnrepository.com/artifact/com.google.android.gms/play-services-tagmanager-v4-impl

This is not an error with this library, but with your Gradle setup.
