### ISSUE TITLE
App hangs on trackScreenViewWithCustomDimensionValues

### ISSUE THREAD

**Issue by zsajjad** [idehub/react-native-google-analytics-bridge#37]
App stops responding on using `GoogleAnalyics.trackScreenViewWithCustomDimensionValues(screen, dimensions)`
Code snippet:

`
   let screen = route.id;
    if(screen === 'screen1'){
      dimensions = {
        '1': route.detail1,
        '2': route.detail2,
        '3': route.detail3
      }
  }
`

**Comment by cbrevik** [comment]
Hi @zsajjad!

Do you have an error message you can share? Maybe from console?

Also I do not understand your code snippet, what is the value of route.detail, etc? Are you trying to send those in as well?

**Comment by zsajjad** [comment]
No error message on console.
route.detail are strings i want to send.

**Comment by cbrevik** [comment]
Can you show me how you call the GoogleAnalytics-method itself? Also is this iOS or Android?

Can you find the error message from XCode or adb logcat?

[Take a look here](https://github.com/idehub/react-native-google-analytics-bridge#google-analytics-logging) on how to enable logging for GA as well.

**Comment by cbrevik** [comment]
@zsajjad is this still a problem? See above comment.

**Comment by zsajjad** [comment]
Resolved that issue. Thanks.
