### ISSUE TITLE
"no versions of com.google.android.gms:play-services-analytics are available"

### ISSUE THREAD

**Issue by GeoffreyPlitt** [idehub/react-native-google-analytics-bridge#38]
Hello,

I believe I've followed all of the instructions on your README, but I'm still having problems.

Things look linked correctly:

webfreelance10@p26xx-webfree10:~/eaplay_good $ rnpm link react-native-google-analytics-bridge
rnpm-link info Android module react-native-google-analytics-bridge is already linked 
rnpm-link info iOS module react-native-google-analytics-bridge is already linked 

But then:

webfreelance10@p26xx-webfree10:~/eaplay_good $ react-native run-android
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-google-analytics-bridge'.
   > Could not resolve all dependencies for configuration ':react-native-google-analytics-bridge:_debugCompile'.
      > Could not find any matches for com.google.android.gms:play-services-analytics:8.+ as no versions of com.google.android.gms:play-services-analytics are available.
        Searched in the following locations:
            file:/Users/webfreelance10/.m2/repository/com/google/android/gms/play-services-analytics/maven-metadata.xml
            file:/Users/webfreelance10/.m2/repository/com/google/android/gms/play-services-analytics/
            https://jcenter.bintray.com/com/google/android/gms/play-services-analytics/maven-metadata.xml
            https://jcenter.bintray.com/com/google/android/gms/play-services-analytics/
            file:/Users/webfreelance10/eaplay_good/node_modules/node_modules/react-native/android/com/google/android/gms/play-services-analytics/maven-metadata.xml
            file:/Users/webfreelance10/eaplay_good/node_modules/node_modules/react-native/android/com/google/android/gms/play-services-analytics/
        Required by:
            EAPlay:react-native-google-analytics-bridge:unspecified
      > Could not find com.android.support:recyclerview-v7:23.0.1.
        Searched in the following locations:
            file:/Users/webfreelance10/.m2/repository/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
            file:/Users/webfreelance10/.m2/repository/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
            https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
            https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
            file:/Users/webfreelance10/eaplay_good/node_modules/node_modules/react-native/android/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
            file:/Users/webfreelance10/eaplay_good/node_modules/node_modules/react-native/android/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
        Required by:
            EAPlay:react-native-google-analytics-bridge:unspecified > com.facebook.react:react-native:0.19.1
      > Could not find com.android.support:appcompat-v7:23.0.1.
        Searched in the following locations:
            file:/Users/webfreelance10/.m2/repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
            file:/Users/webfreelance10/.m2/repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
            https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
            https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
            file:/Users/webfreelance10/eaplay_good/node_modules/node_modules/react-native/android/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
            file:/Users/webfreelance10/eaplay_good/node_modules/node_modules/react-native/android/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
        Required by:
            EAPlay:react-native-google-analytics-bridge:unspecified > com.facebook.react:react-native:0.19.1
      > Could not find com.android.support:support-v4:21.0.3.
        Searched in the following locations:
            file:/Users/webfreelance10/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
            file:/Users/webfreelance10/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
            https://jcenter.bintray.com/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
            https://jcenter.bintray.com/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
            file:/Users/webfreelance10/eaplay_good/node_modules/node_modules/react-native/android/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
            file:/Users/webfreelance10/eaplay_good/node_modules/node_modules/react-native/android/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
        Required by:
            EAPlay:react-native-google-analytics-bridge:unspecified > com.facebook.react:react-native:0.19.1 > com.facebook.fresco:fresco:0.8.1 > com.facebook.fresco:imagepipeline:0.8.1
            EAPlay:react-native-google-analytics-bridge:unspecified > com.facebook.react:react-native:0.19.1 > com.facebook.fresco:fresco:0.8.1 > com.facebook.fresco:drawee:0.8.1

Let me know, thanks!

**Comment by cbrevik** [comment]
Hi @GeoffreyPlitt!

Do you have the [required SDKs installed](https://github.com/idehub/react-native-google-analytics-bridge#prerequisites-for-android)?

**Comment by cbrevik** [comment]
@GeoffreyPlitt is this still a problem? See above comment.

**Comment by GeoffreyPlitt** [comment]
That was the fix, sorry for leaving this open! Thanks.

**Comment by cbrevik** [comment]
Great, thanks man!
