### ISSUE TITLE
Few warnings in adb logcat of GA

### ISSUE THREAD

**Issue by zsajjad** [idehub/react-native-google-analytics-bridge#40]
`adb logcat -v time -s GAv4`

Showing these warnings, i have done all steps mentioned for installation

`05-30 16:37:51.883 W/GAv4    (16184): AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions. 05-30 16:37:51.888 W/GAv4    (16184): CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions. 05-30 16:37:51.899 W/GAv4    (16184): AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.`

**Comment by cbrevik** [comment]
Hi, these are (as it is says) just warnings.

I'll have to consider if this is something I should add by default in the library `AndroidManifest.xml`.

**Comment by sibelius** [comment]
this could help: http://stackoverflow.com/a/30164011/2628278

and this one: https://developers.google.com/analytics/devguides/collection/android/v4/

maybe we can this information to readme

**Comment by nikolaia** [comment]
PRs are welcome
