### ISSUE TITLE
couldn’t find key brand in dynamic object

### ISSUE THREAD

**Issue by einsub** [idehub/react-native-google-analytics-bridge#45]
Hello,

When we use trackPurchaseEvent function, we got this error if we don't provide some of optional arguments.

This error has been occurred only on Android and it's perfectly fine on iOS.

If we provide all of the arguments, it works.

<img width="565" alt="screen shot 2016-07-11 at 17 53 26" src="https://cloud.githubusercontent.com/assets/2919667/16754168/0816d4d4-482b-11e6-8a32-038e9ce021a1.png">

Would you please tell me the best practice?

Thanks.

**Comment by cbrevik** [comment]
Hi @einsub 

As you say you need to provide all arguments. At the moment the implementation for both iOS and Android doesn't do any key-checking in the incoming dictionaries.

A possible enhancement here would be to see if the key exists before retrieving and adding it to the ecommerce-product that is tracked.
