### ISSUE TITLE
ios version and bitcode

### ISSUE THREAD

**Issue by hrlarsen** [idehub/react-native-google-analytics-bridge#5]
Hi

When building for iOS, the minimum version is 8.2, is this on purpose? Would like to see a 7.0 as minimum (same as React)

Also, bitcode is not enabled in the RCTGoogleAnalyticsBridge.xcodeproj, would love to see it being compiled with bitcode enabled.

**Comment by cbrevik** [comment]
Hi!

The iOS version has been mentioned in another issue (#3). No reason other than not noticing the warning myself. I'll consider making 7.0 the default target. 

Bitcode enabled is a good suggestion, but I am unsure of the potential side effects. I will have to look into it.

**Comment by hrlarsen** [comment]
Didn't see that closed issue. And thanks for looking into bitcode.

**Comment by cbrevik** [comment]
Cool! If you have any experience with migrating from non-bitcode to bitcode I'd love to hear it. 

It seems like it shouldn't be an issue, but at the same time some people are mentioning esoteric problems enabling bitcode. I wouldn't want to break the library for people currently implementing it. It would have to be a breaking changes release in that case.

**Comment by cbrevik** [comment]
Tagging @9mm to say I am going to look into making 7.0 the default target soon :)

**Comment by 9mm** [comment]
:) :+1:
