### ISSUE TITLE
[QUESTION] Installed Analytics via cocoapods, can't get app to work

### ISSUE THREAD

**Issue by ospfranco** [idehub/react-native-google-analytics-bridge#51]
Hey, I followed the google guide to install google analytics on iOS via cocoa pods, then followed the steps on the readme.md file (rnmp install and linking libraries), however I can't get the app to work.

I'm getting all sort of duplicate symbols errors.

Any help setting up this to work?

**Comment by ospfranco** [comment]
I completely misunderstood how to install/use the library, there is no need to have the native libraries installed on your xcode project.

HOWEVER, even though I used rnpm the linking to the library was not done automatically, so I had to the manual installation by myself, hopefully this will be useful to someone else.

**Comment by cbrevik** [comment]
Yes, this is correct, the GA lib is bundled with the module. 👍
