### ISSUE TITLE
Help wanted, more dex conflicts

### ISSUE THREAD

**Issue by ospfranco** [idehub/react-native-google-analytics-bridge#52]
Hey, I also got the dex error referenced on #26 , on SafeParcelable package, I added:

compile("com.google.android.gms:play-services-analytics:8.3.0"){
    force = true
}
However now I get this:

Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzjz;

Any ideas con how to solve this?

edit: this are my dependencies

    compile("com.google.android.gms:play-services-analytics:8.3.0"){
      force = true
    }
    compile project(':react-native-google-analytics-bridge')
    compile project(':@remobile/react-native-splashscreen')
    compile project(':@remobile/react-native-toast')
    compile project(':react-native-vector-icons')
    compile project(':react-native-push-notification')
    compile "com.mixpanel.android:mixpanel-android:4.+"
    compile project(':react-native-mixpanel')
    compile project(':react-native-device-info')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-fbsdk')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"

**Comment by cbrevik** [comment]
Hi @ospfranco. Which version of the this library are you using? And which version of RN is this?

**Comment by ospfranco** [comment]
I'm using react-native 0.29.2 and library 2.1.0

**Comment by cbrevik** [comment]
Do you still get the same problem if you include the `react-native-push-notification` package? 

I see they depend on a quite old version of play-services `'com.google.android.gms:play-services-gcm:7.8.0'`.

**Comment by ospfranco** [comment]
I'm guessing you meant excluding the `react-native-push-notification` package, I'm not really familiar with gradle, would you care giving more detailed instructions on how to achieve this?

**Comment by ospfranco** [comment]
ok, I removed the dependency from npm, deleted the `node_modules` folder, modified the gradle build and removed all code references from java code, I'm guessing this is what you meant, and project compiled just fine

**Comment by ospfranco** [comment]
alright, I got it working, my dependencies:

dependencies {
    compile project(':react-native-google-analytics-bridge')
    compile project(':@remobile/react-native-splashscreen')
    compile project(':@remobile/react-native-toast')
    compile project(':react-native-vector-icons')
    compile project(':react-native-push-notification')
    compile ('com.google.android.gms:play-services-gcm:8.+') {
        force = true;
    }
    compile "com.mixpanel.android:mixpanel-android:4.+"
    compile project(':react-native-mixpanel')
    compile project(':react-native-device-info')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-fbsdk')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
}

I had tried using the exact module version (8.3.0) but that threw the same error, now it works.

**Comment by cbrevik** [comment]
Nice!

To be honest the `react-native-push-notification` folks should be updating their dependencies. There are many other modules that uses `play-services`, and as such version conflicts like these are a constant problem if you use two or more modules depending on `play-services`. 

At the moment this module (`v3.0.0`) is depending on `9.+` of `play-services`.

Anywho, I'm closing the issue then since this is not a module-specific problem, and it seems like you got it working?

**Comment by ospfranco** [comment]
While one could make a few points against updating or using dynamic versioning, it seems that google-play packages are retro-compatible with previous versions, so I would agree using the latest version is the easiest path for all libraries that depend on them.

That being said, I'm just glad I got it working, thanks @cbrevik.
