### ISSUE TITLE
Update to Android settings MainActivity.java --> MainApplication.java 

### ISSUE THREAD

**Issue by ajaxmac** [idehub/react-native-google-analytics-bridge#53]
Hi,

First of all, thanks for the most excellent Google Analytics package for React Native!

Second: since React Native v.0.29.0 the settings for Android have changed. 

Previously the settings you have listed at "Register package in MainActivity.java" are now going into "MainApplication.java".

My App was crashing before I figured this out. Just thought I would let you know,

**Comment by cbrevik** [comment]
Resolved with #58
