### ISSUE TITLE
.trackTiming() 'name' is required

### ISSUE THREAD

**Issue by wilsonpage** [idehub/react-native-google-analytics-bridge#55]
Without including the 'optional' `name` value my timing reports never showed up in GA dashboard. [This stackoverflow question](http://stackoverflow.com/questions/18201633/where-to-find-user-timing-reports-for-google-analytics-for-mobile-ios) seems to reinforce this finding.

**Comment by cbrevik** [comment]
Thanks for the heads up. Can't do much except note this in the README. :+1:
