### ISSUE TITLE
Help Needed - How can I send event with this library?

### ISSUE THREAD

**Issue by cubbuk** [idehub/react-native-google-analytics-bridge#57]
how can I send a custom event which I will track using this library? Something similar to following: https://developers.google.com/analytics/devguides/collection/android/v4/events

Thanks

**Comment by nikolaia** [comment]
Did you read the README before posting this question or is it still unclear after reading the README?

What have you tried something that didn't work - can you post any code?

**Comment by cubbuk** [comment]
I read it and build the configuration for android, I set tracker id but I couldn't see any example about sending events, could you let me know if I have missed anything?

```
        GoogleAnalytics.setTrackerId("UA-76956079-1");
        GoogleAnalytics.setDispatchInterval(60);
        GoogleAnalytics.trackEvent('testcategory', 'testaction');
```

**Comment by nikolaia** [comment]
Have you made sure to wait the 60 seconds you've put as the DispatchInterval before quitting the emulator?

**Comment by cubbuk** [comment]
I am working on a real device, but now I see it thanks, I thought this function only notifies for which events to track, but it actually sends the event. Thanks
