### ISSUE TITLE
What's the best place to put trackScreenView code?

### ISSUE THREAD

**Issue by prithsharma** [idehub/react-native-google-analytics-bridge#66]
I tried putting the code in the `constructor` or `componentDidMount` method of a component but those methods aren't called when the user lands on that screen after the initial mount.

Another place could be the `renderScene` method of the navigator. But that has another issue of a screen being tracked multiple times for one render which keeps the sequence of screen views good and traceable in the analytics console but really messes up the total page views or other stats.
Is there another way that I am missing and others have figured out?

**Comment by cbrevik** [comment]
Hi @prithsharma. 

This mostly depends on how you navigate between different screens, as well as lifecycles of your components. 

I'd recommend putting the tracking-call alongside any navigation logic, it doesn't need to be in the component file itself.

**Comment by prithsharma** [comment]
Makes sense.
I tried putting it in the `renderScene` method of my navigator component. But that way, I ended up registering multiple screen views when actually the route was rendered once. Should I take the pain of checking the route stack before actually registering a screen-view? I just thought there must be a more elegant way..

**Comment by cbrevik** [comment]
If you're using the `Navigator` component you may just be able to do it in a [onDidFocus](https://facebook.github.io/react-native/docs/navigator.html#ondidfocus)-callback after a transition?

I've never used it myself, but it's worth a try.

**Comment by naiyt** [comment]
For anybody else who ends up here, I tried the `onDidFocus` callback and it seems to be working well. What I've got is essentially:

```javascript
_focusedOn(route) {
    GoogleAnalytics.trackScreenView(route.name);
}

render() {
    <Navigator
       // ...all my other navigator props
       onWillFocus={this._focusedOn} />
}
```

I haven't tried it in production for two long, but it's a nice simple solution that seems to resolve the issues @prithsharma mentioned with the other options.

**Comment by cbrevik** [comment]
Thanks for the feedback @naiyt, I am sure it will be helpful!
