### ISSUE TITLE
Error when I set setTrackUncaughtExceptions to true

### ISSUE THREAD

**Issue by DonovanCharpin** [idehub/react-native-google-analytics-bridge#74]
Hi guys, I just downloaded the last release of the library and I get this error when I call 

```
GoogleAnalyticssetTrackUncaughtExceptions(true);
```

with this stacktrace

```
index.ios.bundle:24542RCTGoogleAnalyticsBridge. was called with 2 arguments, but expects 1.                   
If you haven't changed this method yourself, this usually means that  your versions of the native code and JavaScript code are out of sync.
Updating both should make this error go 

away.reactConsoleError @ index.ios.bundle:24542
console.error @ index.ios.bundle:63197
logIfNoNativeHook @ index.ios.bundle:25148
__callFunction @ index.ios.bundle:3818
(anonymous function) @ index.ios.bundle:3689guard @ index.ios.bundle:3629
callFunctionReturnFlushedQueue @ index.ios.bundle:3688
onmessage @ debuggerWorker.js:44
```

It says that my native code and javascript code are out of sync, do you have any idea? :)

**Comment by cbrevik** [comment]
Hi @DonovanCharpin 

Normally this should be fixed if you just re-run the RN package manager. Basically just shut everything down and restart the app. Is this still a problem?

**Comment by codyhazelwood** [comment]
`GoogleAnalytics.setTrackUncaughtExceptions(true);` crashes in iOS but does not crash in Android.

I tried restarting the RN package manager, restarting Xcode, cleaning the build, and removing and relinking `react-native-google-analytics-bridge`.

**Comment by DonovanCharpin** [comment]
Hi guys,

Sorry I didn't test the app this week. I've seen it's set to true by default so it was fine for me.

**Comment by cbrevik** [comment]
It does indeed default to `true`. But I think we might actually have a bug here, I'll look into it.
