### ISSUE TITLE
GoogleAnalyticsBridge was called with 2 arguments, but expects 1 (iOS)

### ISSUE THREAD

**Issue by codyhazelwood** [idehub/react-native-google-analytics-bridge#75]
I just installed this library with RN 0.36.  

Steps:
- `npm install --save react-native-google-analytics-bridge`
- `react-native link react-native-google-analytics-bridge`

It's working fine in Android.  In iOS, I had to manually add all of the frameworks (CoreData, sqlite, etc).  It builds, but as soon as the app runs, I get:
```
GoogleAnalyticsBridge. was called with 2 arguments, but expects 1.  If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync.  Updating both should make this error go away.
```

Any suggestions?

**Comment by cbrevik** [comment]
What version of this library are you using?

**Comment by codyhazelwood** [comment]
3.1.0

**Comment by cbrevik** [comment]
And what are you doing as you get this error? Code sample?

**Comment by codyhazelwood** [comment]
Duplicate of #74
