### ISSUE TITLE
Logging while dryRun(true)

### ISSUE THREAD

**Issue by tioback** [idehub/react-native-google-analytics-bridge#85]
Hi, 

It'd be a good feature if the app logged the actions it is blocking while dry running.

Does that seem acceptable?

Cheers and thanks for the great component :-)

**Comment by cbrevik** [comment]
Well with [verbose logging](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Troubleshooting) for iOS you should still get tracking logged even while dry running. For logging on Android see [this link](https://developers.google.com/analytics/devguides/collection/android/v4/advanced#logger). 

Dry run is a feature of the native GA library, and so it is not this module while is explicitly blocking hits. So it's probably good enough to just use the normal logs?
