### ISSUE TITLE
Android build failing

### ISSUE THREAD

**Issue by dannycochran** [idehub/react-native-google-analytics-bridge#86]
in android/app/build.gradle:

`
compile project(':react-native-google-analytics-bridge')
`

in android/build.gradle:

`
classpath 'com.google.gms:google-services:3.0.0'
`

Get the following error when running react-native run-android:

`
java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzac; or its super classes (declaration of 'com.google.android.gms.common.internal.zzac' appears in /data/app/com.danny.myapp-1/base.apk)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-21 17:11:33.320 20625 20625 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-21 17:11:33.321  1590 20312 W ActivityManager:   Force finishing activity com.danny.myapp-1/.MainActivity
`

If I change react-native-google-analytics-bridge to use google-analytics 9.6.1 instead of '+' (line 21 in ./android/build.gradle), the issue is resolved.

Is it standard to use + or can we fix to 9.6.1 or 9.8? I believe 10.0 is brand new.

**Comment by ptomasroos** [comment]
You should just force whatever version you want.

In app/build.gradle inside dependencies {}
```
    compile ('com.google.android.gms:play-services-ads:9.6.1') {
        force = true;
    }
    compile ('com.google.android.gms:play-services-gcm:9.6.1') {
        force = true;
    }
```

**Comment by dannycochran** [comment]
that results in a new error, with the following dependencies:

`
dependencies {
    compile project(':react-native-google-analytics-bridge')

    compile 'com.facebook.stetho:stetho:1.3.1'
    compile 'com.facebook.stetho:stetho-okhttp3:1.3.1'

    compile project(':react-native-vector-icons')
    compile project(':react-native-material-kit')
    compile(project(':react-native-google-signin')) {
        exclude group: "com.google.android.gms"
    }
    compile ('com.google.android.gms:play-services:9.6.1') {
        force = true;
    }
    compile ('com.google.android.gms:play-services-ads:9.6.1') {
        force = true;
    }
    compile ('com.google.android.gms:play-services-gcm:9.6.1') {
        force = true;
    }
    // should be at least 9.0.0
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.firebase:firebase-core:9.6.1'
    // From node_modules
}
`

results in this error:

`
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzaj;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzaj;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
`

**Comment by cbrevik** [comment]
I think that might be because `play-services-ads` and `play-services-gcm` are included under `play-services` (which you've also added).

This module requires `play-services-analytics`. Unless you have something that requires all of `play-services`, I would instead change that to `play-services-analytics`.

Do you need `play-services-ads` and `play-services-gcm`?

Normally, these problems are because of conflicting dependencies on `play-services` with other RN modules. See: [Troubleshooting](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Troubleshooting#android-build-problem).

**Comment by cbrevik** [comment]
Stale issue. Closing.

**Comment by zxymgl** [comment]
I met the same problem.
in android/app/build.gradle:
```
dependencies {
    compile project(':react-native-fetch-blob')
    compile project(':react-native-view-shot')
    compile project(':react-native-share')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+" // From node_modules
    compile project(':RCTYouTube') // From node_modules
    compile project(':react-native-linear-gradient')
    compile project(':react-native-push-notification')
    compile ('com.google.android.gms:play-services-gcm:9.0.0') {
        force = true;
    }
   compile ('com.google.android.gms:play-services-ads:9.0.0') {
        force = true;
    }
    compile project(':react-native-google-analytics-bridge')
    compile(project(":react-native-google-signin")){
        exclude group: "com.google.android.gms" // very important
    }
    compile project(':react-native-facebook-login')
    compile 'com.google.android.gms:play-services-auth:9.0.0'

}

```
in android/build.gradle:
`   dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.google.gms:google-services:3.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}`
 
![image](https://cloud.githubusercontent.com/assets/10022573/22182109/7917b15e-e0d7-11e6-9734-a5f289abd660.png)

**Comment by cbrevik** [comment]
All `play-services` dependencies must be the same version. This module uses `play-services-analytics`. See [Troubleshooting](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Troubleshooting#android-build-problem)
