### ISSUE TITLE
Example not working for creating new GoogleAnalyticsTracker

### ISSUE THREAD

**Issue by SMJ93** [idehub/react-native-google-analytics-bridge#88]
In the example it says to:

```
import { GoogleAnalyticsTracker } from 'react-native-google-analytics-bridge';
let tracker = new GoogleAnalyticsTracker('UA-12345-1');

tracker.trackScreenView('Home');
tracker.trackEvent('testcategory', 'testaction');
```

But in the react-native-google-analytics-bridge code it requires 2 fields:

```
constructor(trackerId, customDimensionsFieldsIndexMap) {
    this.id = trackerId;
    this.customDimensionsFieldsIndexMap = customDimensionsFieldsIndexMap;
}
```

When running the example code in my app I get the error: `Cannot read property 'getScrollableNode' of undefined`

In my IDE it says it requires 2 arguments:

![screen shot 2016-11-25 at 16 24 38](https://cloud.githubusercontent.com/assets/2145641/20631004/5e02aa1e-b32c-11e6-8951-29ff787f6f64.png)

**Comment by cbrevik** [comment]
Hi @SMJ93,

Do you have a more complete error message? 

I'm not sure the error `Cannot read property 'getScrollableNode' of undefined` is connected to my module. Are you perhaps using `react-native-scrollable-tab-view`? See https://github.com/skv-headless/react-native-scrollable-tab-view/issues/465

The constructor for the tracker *can* take 2 arguments yes, but it really only needs the `trackerId` unless you are working with custom dimensions. See the API docs for more info about that: https://github.com/idehub/react-native-google-analytics-bridge#new-googleanalyticstrackertrackerid-customdimensionsfieldsindexmap--

**Comment by SMJ93** [comment]
Hi @cbrevik,

Sorry, I am new to react native - do you know any good error debugging tools which return the full error message?

No I am not using the `react-native-scrollable-tab-view` plugin, but if I move the code outside of the component class it runs fine. So I think there is a problem with running this code from inside the `componentDidMount() {` function.

I will investigate further and comment back here.

**Comment by cbrevik** [comment]
Well if you got it in a "red error screen" in the emulator, it should say where the error originated from.

Other than that, I would recommend attaching to the Chrome debugger, and step through your app.

Do you have a more complete code example of what you are doing?

**Comment by SMJ93** [comment]
@cbrevik 
I enabled "Pause on Caught Exceptions" in Chrome which helped me debug this - turns out the problem was with `pushwoosh-react-native-plugin`.

Thanks for your help and great plugin!
