### ISSUE TITLE
'trackScreenViewWithCustomDimensionValues' not work

### ISSUE THREAD

**Issue by Tomatoo** [idehub/react-native-google-analytics-bridge#92]
hi, i use trackScreenViewWithCustomDimensionValues to track page view with custom dimension,but i can only get page view, not get custom dimension in google analysis control panel.

code:
```
GoogleAnalyticsSettings.setDispatchInterval(10);

export function trackScreenView(route) {
  let tracker = new GoogleAnalyticsTracker('XXX', {
    test: 1
  });
  tracker.trackScreenViewWithCustomDimensionValues(getScreenName(route), {test: 'beta'});
}
```
thanks.

**Comment by cbrevik** [comment]
Hi @Tomatoo. I haven't had any other complaints, so I think it should work as intended. Is this still a problem?

**Comment by simonhintersonnleitner** [comment]
it will not work for me too.

**Comment by cbrevik** [comment]
Open a new issue if this is still a problem.
