### ISSUE TITLE
What's the best practice for users logging out?

### ISSUE THREAD

**Issue by kfiroo** [idehub/react-native-google-analytics-bridge#95]
Hey!
When my app starts, and I have a user in session, I call `setUser` with the proper unique id, this part is peachy :)

My question is what should I do if the user logs out?

I could start a new `tracker`, which I guess will have an anonymous user until I call `setUser` on it, but will be missing the current `ScreenView` for instance, not sure what else would be missing.

I could try to set user with an `empty string` / `null` value? (not sure it a good idea)

Any suggestions would be great :)

**Comment by cbrevik** [comment]
Hi @kfiroo. You'll just have to test it, I cannot find any documentation on the subject.

It seems like `null` would be the better value though. Empty string is generally not a good idea.

**Comment by sibelius** [comment]
@kfiroo did u figure it out?

**Comment by kfiroo** [comment]
@sibelius Hey, we ended up not using this lib so I didn't try it.
But as @cbrevik said, `null` is probably the better option

**Comment by sibelius** [comment]
@kfiroo can we close this?

**Comment by kfiroo** [comment]
@sibelius Sure.
Just note that the question is still unanswered :)

**Comment by cbrevik** [comment]
This is better answered by Google docs than by me, as I am just wrapping the original library. Internals there and best practices are a bit unknown. Closing issue.
