### ISSUE TITLE
Unable to call any methods

### ISSUE THREAD

**Issue by bfarrgaynor** [idehub/react-native-google-analytics-bridge#97]
I seem to have this issue where anytime I try to call any of the methods I'm getting undefined, no matter where I place it....

Here is a console log showing in line 1 that I can evaluate the contents of my tracker object. Line 2 is me trying to call trackEvent and I get a undefined. Can't explain it.
https://www.dropbox.com/s/afq6pj215jwrp4d/Screenshot%202017-01-06%2016.23.31.png?dl=0

**Comment by em222iv** [comment]
+1

**Comment by johannalee** [comment]
have you done [manual installations](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Manual-installation)?

**Comment by em222iv** [comment]
Yes, it actually seems to work with ios. Just now with android

**Comment by johannalee** [comment]
@em222iv what are you failing with android?

**Comment by em222iv** [comment]
The following code in index.ios/index.android files breaks the build on android but not in ios for RN: 39.02.
<img width="591" alt="code" src="https://cloud.githubusercontent.com/assets/5379414/21936673/625e3f54-d9b2-11e6-9482-7cb61a116aa0.png">
<img width="327" alt="error" src="https://cloud.githubusercontent.com/assets/5379414/21936672/625a455c-d9b2-11e6-909c-5e8b481ce0a1.png">

**Comment by cbrevik** [comment]
@em222iv Can you verify that `settings.gradle`, `build.gradle` & `MainApplication.java` have all the additions that are described in the [manual install for Android](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Manual-installation#manual-installation-android)?

**Comment by em222iv** [comment]
I can confirm that I have followed the manual installation for android.

app/build.gradle:
<img width="456" alt="add build grade" src="https://cloud.githubusercontent.com/assets/5379414/21975684/472be1be-dbce-11e6-898f-587bf0420645.png">
mainApplication
<img width="364" alt="mainapp1" src="https://cloud.githubusercontent.com/assets/5379414/21975687/472f93c2-dbce-11e6-95a8-9e13b854f570.png">
mainApplication
<img width="572" alt="mainapp2" src="https://cloud.githubusercontent.com/assets/5379414/21975685/472bf564-dbce-11e6-846f-5eabfa9645b1.png">
settings.gradle
<img width="1207" alt="android settings gradle" src="https://cloud.githubusercontent.com/assets/5379414/21975686/472c168e-dbce-11e6-9439-28ebf5fcd99d.png">

I have used this library in multiple project but this is the first time this behaviour shows up.

**Comment by bfarrgaynor** [comment]
Mine fails in iOS too. Manual installation.

**Comment by cbrevik** [comment]
Which RN versions, and which versions of this module are you using?

I'd recommend just trying to `react-native init` some sample project, then installing + linking this module there to see if the same happens. If it is limited to just one project, I'd recommend trying to install it again.

**Comment by bfarrgaynor** [comment]
RN 0.39.2
This package (analytics) 4.0.2

**Comment by lakhman** [comment]
I also got this error using the following:

```
GoogleTagManager.pushDataLayerEvent({event: "someEvent"})
            .then((success) => console.log(success)); // Removing this fixed it.
```

Removing the `.then` fixed it (temporarily).

I double checked my configuration, everything is linked as expected.
This was on iOS.

```
    "react": "^15.4.1",
    "react-native": "^0.38.1",
    "react-native-google-analytics-bridge": "^4.0.2",
```

```
$ react-native --version
react-native-cli: 1.3.0
react-native: 0.38.1
```

**Comment by cbrevik** [comment]
Are any of you able to provide a sample project for this error? I am not able to reproduce this.

**Comment by ericnograles** [comment]
Hey guys,

I'm not sure if this is the root cause of your issues, but if you're on React Native prior to 0.40, the latest (5.0.0) release of this library will _not_ work.  The reason is React Native 0.40 basically introduced a breaking change to iOS with the header declarations.

I'm on React Native 0.38 and am using the [4.0.0 version](https://github.com/idehub/react-native-google-analytics-bridge/tree/v4.0.0) of this library ok on iOS, gonna check my Android builds shortly.

hth,

Eric

**Comment by mcmatan** [comment]
Same as @ericnograles  for me version 5.0 does not work (IOS) downgraded to 4.0 and all good.

**Comment by cbrevik** [comment]
Can any of you provide a sample project that can reproduce this?

All 5.0 does is change the header imports for RN 0.40+. Everyone on less than RN > 0.39 should not use 5.0.

**Comment by dasblitz** [comment]
I have a similar issue running on iOS using react-native 0.34.1 with react-native-google-analytics-bridge 4.0.3. 

When I start my emulator from the console using `$ react-native run-ios` 

`const tracker = new GoogleAnalyticsTracker('UA-XXXXXXXX-X');`

The tracker has only the `id` and `customDimensionsFieldsIndexMap` properties

calling `tracker.trackScreenView('SCREEN_NAME')` throws an undefined error

When I start the emulator from XCode the same code is working however (Google Analytics realtime dashboard correctly displays the screens I'm passing it).

Is there some debug setting I missed?

**Comment by ankitvadariya** [comment]
Conclusion : it will work on only release APK or IPA .
It will not work with react native bridge

**Comment by cbrevik** [comment]
This is a catch-all issue without any real code to reproduce. If anyone else is experiencing this problem, please open a new issue with actual code/project to reproduce.
